
CREATE TABLE TASK_DEFINITIONS  (
	DEFINITION_NAME VARCHAR(255) NOT NULL PRIMARY KEY,
	DEFINITION TEXT DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE STREAM_DEFINITIONS  (
	DEFINITION_NAME VARCHAR(255) NOT NULL PRIMARY KEY,
	DEFINITION TEXT DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE DEPLOYMENT_IDS  (
	DEPLOYMENT_KEY VARCHAR(255) NOT NULL PRIMARY KEY,
	DEPLOYMENT_ID VARCHAR(255) NOT NULL
)ENGINE=InnoDB;
