#!/bin/sh

# ----------------------------------------------------------------------------
# Script maintaining versions
#
# Bump up next minor development version for parents.
# ----------------------------------------------------------------------------

find_basedir() {
  local basedir=$(cd -P -- "$(dirname -- "$0")" && cd .. && cd .. && pwd -P)
  echo "${basedir}"
}

export PROJECTBASEDIR=$(find_basedir)

(cd $PROJECTBASEDIR && ./mvnw build-helper:parse-version versions:update-parent -DgenerateBackupPoms=false -DallowSnapshots=true -DparentVersion='${parsedVersion.majorVersion}.${parsedVersion.nextMinorVersion}')

