{
 "title": "SCDF Streams",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "stream",
    "label": "Stream",
    "query": "select distinct(\"stream_name\") from (select  * from \"spring_integration_send\" WHERE time > now() - 60s)"
   },
   {
    "name": "application",
    "label": "application",
    "query": "show tag values with key=\"application_name\" WHERE stream_name='$stream'"
   },
   {
    "name": "application_id",
    "label": "ApplicationId",
    "query": "show tag values from \"spring_integration_send\" with key = \"application_guid\" WHERE stream_name = '$stream'"
   },
   {
    "name": "streamCount",
    "query": "SHOW TAG VALUES CARDINALITY FROM \"spring_integration_send\" WITH KEY = \"application_name\""
   },
   {
    "name": "copy_of_stream",
    "label": "Stream",
    "query": "show tag values with key=\"stream_name\""
   }
  ]
 },
 "panels": [
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# Streams",
   "type": "singlestat",
   "description": "Number of deployed streams",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "spring_integration_send",
     "query": "SELECT count(*)  FROM (SELECT  count(\"count\") FROM \"autogen\".\"spring_integration_send\" GROUP BY \"stream_name\") WHERE time > now() - 1m\n",
     "select": [
      [
       { "params": [ "/^$streamCount$/" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Running Streams",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 2, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select distinct(\"stream_name\") as \"streams\" from (select  * from \"spring_integration_send\" WHERE time > now() - 60s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Apps",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 5, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT distinct(\"application_name\")  as \"apps\" FROM (SELECT * FROM \"autogen\".\"spring_integration_send\" WHERE  (\"stream_name\" =~ /^$stream$/ )  group by application_name)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Channel Errors",
   "type": "graph",
   "description": "Channel Errors across all Streams and Apps",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "spring_integration_send",
     "query": "SELECT \"count\"  / 60 FROM \"spring_integration_send\" WHERE (\"stream_name\" =~ /^$stream$/ AND \"application_name\" =~ /^$application$/ AND \"type\" = 'channel' AND \"name\" = 'errorChannel') AND $timeFilter GROUP BY \"stream_name\", \"application_name\", \"result\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "channel" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "errorChannel" }
     ]
    }
   ]
  },
  {
   "title": "Process CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" }
     ],
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" }
     ],
     "measurement": "process_files_open",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "# Apps per Stream",
   "type": "singlestat",
   "description": "Number of running Applications for selected streams",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "spring_integration_send",
     "query": "SELECT count(distinct(application_name)) FROM (SELECT * FROM \"autogen\".\"spring_integration_send\" WHERE  (\"stream_name\" =~ /^$stream$/ )  group by application_name)",
     "select": [
      [
       { "params": [ "/^$streamCount$/" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "spring_integration_send",
     "query": "SELECT count(\"count\")  / 60 FROM \"spring_integration_send\" WHERE (\"stream_name\" =~ /^$stream$/ AND \"type\" = 'channel' AND \"application_name\" =~ /^$application$/ AND \"result\" = 'success' AND ( \"name\" = 'output' OR \"name\" = 'input')) AND $timeFilter GROUP BY \"application_name\", \"result\", \"application_name\", \"name\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "name", "operator": "!=", "value": "errorChannel" }
     ]
    }
   ]
  },
  {
   "title": "Channel Errors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"count\"  / 60 FROM \"spring_integration_send\" WHERE (\"stream_name\" =~ /^$stream$/ AND \"application_name\" =~ /^$application$/ AND \"type\" = 'channel' AND \"name\" = 'errorChannel') AND $timeFilter GROUP BY \"stream_name\", \"application_name\", \"result\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Channels (Success)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Channels Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "result" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "spring_integration_send",
     "query": "SELECT \"count\"  / 60 FROM \"spring_integration_send\" WHERE (\"stream_name\" =~ /^$stream$/ AND \"type\" = 'channel' AND \"application_name\" =~ /^$application$/ AND \"result\" = 'success' AND ( \"name\" = 'output' OR \"name\" = 'input')) AND $timeFilter GROUP BY \"application_name\", \"result\", \"application_name\", \"name\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "channel" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "output" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "input" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "success" }
     ]
    }
   ]
  },
  {
   "title": "Channels Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "result" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "spring_integration_send",
     "query": "SELECT \"mean\" FROM \"spring_integration_send\" WHERE (\"stream_name\" =~ /^$stream$/ AND \"application_name\" =~ /^$application$/ AND \"type\" = 'channel' AND \"result\" = 'success' AND ( \"name\" = 'output' OR \"name\" = 'input')) AND $timeFilter GROUP BY \"stream_name\", \"application_name\", \"result\", \"name\"",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "channel" }
     ]
    }
   ]
  },
  { "title": "Error Channels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Error Channel Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "spring_integration_send",
     "query": "SELECT \"count\"  / 60 FROM \"spring_integration_send\" WHERE (\"stream_name\" =~ /^$stream$/ AND \"application_name\" =~ /^$application$/ AND \"type\" = 'channel' AND \"name\" = 'errorChannel') AND $timeFilter GROUP BY \"stream_name\", \"application_name\", \"result\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "channel" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "errorChannel" }
     ]
    }
   ]
  },
  {
   "title": "Error Channel Average Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "spring_integration_send",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "channel" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "errorChannel" }
     ]
    }
   ]
  },
  { "title": "Handlers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Handlers Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "result" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "spring_integration_send",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "handler" },
      {
       "condition": "AND",
       "key": "name",
       "operator": "!=",
       "value": "org_springframework_cloud_stream_app_log_sink_LogSinkConfiguration_logSinkHandler_serviceActivator_handler"
      }
     ]
    }
   ]
  },
  {
   "title": "Handlers Average Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "result" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "spring_integration_send",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "handler" },
      {
       "condition": "AND",
       "key": "name",
       "operator": "!=",
       "value": "org_springframework_cloud_stream_app_log_sink_LogSinkConfiguration_logSinkHandler_serviceActivator_handler"
      }
     ]
    }
   ]
  }
 ]
}