{
 "title": "Applications",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "stream_name",
    "label": "stream",
    "query": "select distinct(\"stream_name\") from (select  * from \"spring_integration_send\" WHERE time > now() - 60s)"
   },
   {
    "name": "application_name",
    "label": "application",
    "query": "show tag values with key=\"application_name\" WHERE stream_name='$stream_name'"
   },
   {
    "name": "name",
    "label": "name",
    "query": "show tag values with key=\"name\" WHERE stream_name='$stream_name' AND application_name='$application_name'"
   },
   {
    "name": "application_guid",
    "label": "guid",
    "query": "show tag values from \"spring_integration_send\" with key = \"application_guid\" WHERE stream_name = '$stream_name'"
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# Apps",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(process_cpu_usage{stream_name=~\"$stream_name\",application_name=~\"$application_name\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(application_name)) FROM (SELECT * FROM \"autogen\".\"spring_integration_send\" WHERE  (\"stream_name\" =~ /^$stream_name$/ )  group by application_name)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 2, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_application_name [$tag_application_guid]",
     "expr": "avg(process_cpu_usage{stream_name=~\"$stream_name\",application_name=~\"$application_name\"}) by (application_name,application_guid)",
     "groupBy": [
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "application_guid" ], "type": "tag" }
     ],
     "legendFormat": "{{application_name}} [{{application_guid}}]",
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream_name$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_application_name [$tag_application_guid]",
     "expr": "avg(jvm_memory_used_bytes{stream_name=~\"$stream_name\",application_name=~\"$application_name\"}) by (application_name,application_guid)",
     "groupBy": [
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "application_guid" ], "type": "tag" }
     ],
     "legendFormat": "{{application_name}} [{{application_guid}}]",
     "measurement": "jvm_memory_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream_name$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_application_name [$tag_application_guid]",
     "expr": "avg(jvm_threads_live_threads{stream_name=~\"$stream_name\",application_name=~\"$application_name\"}) by (application_name,application_guid)",
     "groupBy": [
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "application_guid" ], "type": "tag" }
     ],
     "legendFormat": "{{application_name}} [{{application_guid}}]",
     "measurement": "jvm_threads_live",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream_name$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Files",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_application_name [$tag_application_guid]",
     "expr": "avg(process_files_open_files{stream_name=~\"$stream_name\",application_name=~\"$application_name\"}) by (application_name,application_guid)",
     "groupBy": [
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "application_guid" ], "type": "tag" }
     ],
     "legendFormat": "{{application_name}} [{{application_guid}}]",
     "measurement": "process_files_open",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream_name$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Classes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_application_name [$tag_application_guid]",
     "expr": "avg(jvm_classes_loaded_classes{stream_name=~\"$stream_name\",application_name=~\"$application_name\"}) by (application_name,application_guid)",
     "groupBy": [
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "application_guid" ], "type": "tag" }
     ],
     "legendFormat": "{{application_name}} [{{application_guid}}]",
     "measurement": "jvm_classes_loaded",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream_name$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application_name$/" }
     ]
    }
   ]
  },
  { "title": "Applications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 7 },
   "repeat": "application_name",
   "content": "<p style=\"text-align: center;font-size: 200%;color:#299c46;\" > $application_name </p>"
  },
  {
   "title": "Channel Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "repeat": "application_name",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_application_name [$tag_name]",
     "expr": "rate(spring_integration_send_seconds_count{type=\"channel\",name!=\"errorChannel\",name!=\"nullChannel\",result=\"success\",stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}[60s])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{name}} [{{application_guid}}]",
     "query": "SELECT \"count\"  / 60 FROM \"spring_integration_send\" WHERE (\"stream_name\" =~ /^$stream_name$/ AND \"type\" = 'channel' AND \"application_name\" =~ /^$application_name$/ AND \"application_guid\" =~ /^$application_guid$/ AND \"result\" = 'success' AND ( \"name\" = 'output' OR \"name\" = 'input')) AND $timeFilter GROUP BY \"application_name\", \"name\", \"application_guid\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Channel Latency",
   "type": "graph",
   "description": "($application_name)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "repeat": "application_name",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "[$tag_name] $tag_application_name ($tag_application_guid)",
     "expr": "spring_integration_send_seconds_sum{type=\"channel\", stream_name=~\"$stream_name\",application_name=~\"$application_name\"}/spring_integration_send_seconds_count{type=\"channel\", stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{name}} [{{application_guid}}]",
     "query": "SELECT \"mean\" FROM \"spring_integration_send\" WHERE (\"stream_name\" =~ /^$stream_name$/ AND \"application_name\" =~ /^$application_name$/ AND \"type\" = 'channel' AND \"application_guid\" =~ /^$application_guid$/ AND \"result\" = 'success' AND ( \"name\" = 'output' OR \"name\" = 'input')) AND $timeFilter GROUP BY \"stream_name\", \"application_name\", \"application_guid\", \"result\", \"name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Handler Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "repeat": "application_name",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name [$tag_application_guid]",
     "expr": "rate(spring_integration_send_seconds_count{type=\"handler\",result=\"success\",stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}[60s])",
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "application_guid" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "legendFormat": "{{name}} [{{application_guid}}]",
     "measurement": "spring_integration_send",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream_name$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application_name$/" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "success" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "handler" }
     ]
    }
   ]
  },
  {
   "title": "Message Source Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "repeat": "application_name",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name [$tag_application_guid]",
     "groupBy": [
      { "params": [ "application_guid" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "application_guid" ], "type": "tag" }
     ],
     "measurement": "spring_integration_receive",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream_name$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application_name$/" },
      { "condition": "AND", "key": "application_guid", "operator": "=~", "value": "/^$application_guid$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "source" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "success" }
     ]
    }
   ]
  },
  {
   "title": "Channel  Failures",
   "type": "graph",
   "description": "($application_name)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "repeat": "application_name",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name [$tag_application_guid]",
     "expr": "rate(spring_integration_send_seconds_count{type=\"channel\",result=\"failure\",stream_name=~\"$stream_name\",application_name=~\"$application_name\",application_guid=~\"$application_guid\"}[60s])",
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "application_guid" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "legendFormat": "{{name}} [{{application_guid}}]",
     "measurement": "spring_integration_send",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream_name$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application_name$/" },
      { "condition": "AND", "key": "application_guid", "operator": "=~", "value": "/^$application_guid$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "channel" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "failure" }
     ]
    }
   ]
  },
  {
   "title": "Channels, Handlers, Sources Counts",
   "type": "graph",
   "description": "($application_name)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "repeat": "application_name",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "#channels [$tag_application_guid]",
     "expr": "spring_integration_channels{stream_name=~\"$stream_name\", application_name=~\"$application_name\", application_guid=~\"$application_guid\"}",
     "groupBy": [
      { "params": [ "application_guid" ], "type": "tag" }
     ],
     "legendFormat": "#channels [{{application_guid}}]",
     "measurement": "spring_integration_channels",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream_name$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application_name$/" },
      { "condition": "AND", "key": "application_guid", "operator": "=~", "value": "/^$application_guid$/" }
     ]
    },
    {
     "alias": "#handlers [$tag_application_guid]",
     "expr": "spring_integration_handlers{stream_name=~\"$stream_name\", application_name=~\"$application_name\", application_guid=~\"$application_guid\"}",
     "groupBy": [
      { "params": [ "application_guid" ], "type": "tag" }
     ],
     "legendFormat": "#handlers [{{application_guid}}]",
     "measurement": "spring_integration_handlers",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream_name$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application_name$/" },
      { "condition": "AND", "key": "application_guid", "operator": "=~", "value": "/^$application_guid$/" }
     ]
    },
    {
     "alias": "#sources [$tag_application_guid]",
     "expr": "spring_integration_sources{stream_name=~\"$stream_name\", application_name=~\"$application_name\", application_guid=~\"$application_guid\"}",
     "groupBy": [
      { "params": [ "application_guid" ], "type": "tag" }
     ],
     "legendFormat": "#sources [{{application_guid}}]",
     "measurement": "spring_integration_sources",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream_name$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application_name$/" },
      { "condition": "AND", "key": "application_guid", "operator": "=~", "value": "/^$application_guid$/" }
     ]
    }
   ]
  }
 ]
}