{
 "title": "Applications",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "stream",
    "label": "Stream",
    "query": "select distinct(\"stream_name\") from (select  * from \"spring_integration_send\" WHERE time > now() - 60s)"
   },
   {
    "name": "application",
    "label": "application",
    "query": "show tag values with key=\"application_name\" WHERE stream_name='$stream'"
   },
   {
    "name": "application_id",
    "label": "ApplicationId",
    "query": "show tag values from \"spring_integration_send\" with key = \"application_guid\" WHERE stream_name = '$stream'"
   },
   {
    "name": "streamCount",
    "query": "SHOW TAG VALUES CARDINALITY FROM \"spring_integration_send\" WITH KEY = \"application_name\""
   },
   {
    "name": "copy_of_stream",
    "label": "Stream",
    "query": "show tag values with key=\"stream_name\""
   }
  ]
 },
 "panels": [
  {
   "title": "System ($stream / $application)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "application"
  },
  {
   "title": "CPU  $stream / $application",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" }
     ],
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads ($stream/$application)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" }
     ],
     "measurement": "jvm_threads_live",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" }
     ],
     "measurement": "jvm_threads_daemon",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory ($stream/$application)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Open Files ($stream/$application)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" }
     ],
     "measurement": "process_files_open",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "System ($stream / $application)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "CPU  $stream / $application",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" }
     ],
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads ($stream/$application)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" }
     ],
     "measurement": "jvm_threads_live",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" }
     ],
     "measurement": "jvm_threads_daemon",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory ($stream/$application)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Open Files ($stream/$application)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" }
     ],
     "measurement": "process_files_open",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "System ($stream / $application)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "CPU  $stream / $application",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" }
     ],
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads ($stream/$application)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" }
     ],
     "measurement": "jvm_threads_live",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" }
     ],
     "measurement": "jvm_threads_daemon",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory ($stream/$application)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Open Files ($stream/$application)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" }
     ],
     "measurement": "process_files_open",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Channels ($stream / $application)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "repeat": "application"
  },
  {
   "title": "Throughput",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "spring_integration_send",
     "query": "SELECT count(\"count\")  / 60 FROM \"spring_integration_send\" WHERE (\"stream_name\" =~ /^$stream$/ AND \"type\" = 'channel' AND \"application_name\" =~ /^$application$/ AND \"result\" = 'success' AND ( \"name\" = 'output' OR \"name\" = 'input')) AND $timeFilter GROUP BY \"application_name\", \"result\", \"application_name\", \"name\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "name", "operator": "!=", "value": "errorChannel" }
     ]
    }
   ]
  },
  {
   "title": "($stream/$application) Channel Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 3, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "result" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "spring_integration_send",
     "query": "SELECT \"count\"  / 60 FROM \"spring_integration_send\" WHERE (\"stream_name\" =~ /^$stream$/ AND \"type\" = 'channel' AND \"application_name\" =~ /^$application$/ AND \"result\" = 'success' AND ( \"name\" = 'output' OR \"name\" = 'input')) AND $timeFilter GROUP BY \"application_name\", \"result\", \"application_name\", \"name\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "channel" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "output" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "input" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "success" }
     ]
    }
   ]
  },
  {
   "title": "($stream/$application) Channel Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "result" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "spring_integration_send",
     "query": "SELECT \"mean\" FROM \"spring_integration_send\" WHERE (\"stream_name\" =~ /^$stream$/ AND \"application_name\" =~ /^$application$/ AND \"type\" = 'channel' AND \"result\" = 'success' AND ( \"name\" = 'output' OR \"name\" = 'input')) AND $timeFilter GROUP BY \"stream_name\", \"application_name\", \"result\", \"name\"",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "channel" }
     ]
    }
   ]
  },
  {
   "title": "Channels ($stream / $application)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }
  },
  {
   "title": "Throughput",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 36 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "spring_integration_send",
     "query": "SELECT count(\"count\")  / 60 FROM \"spring_integration_send\" WHERE (\"stream_name\" =~ /^$stream$/ AND \"type\" = 'channel' AND \"application_name\" =~ /^$application$/ AND \"result\" = 'success' AND ( \"name\" = 'output' OR \"name\" = 'input')) AND $timeFilter GROUP BY \"application_name\", \"result\", \"application_name\", \"name\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "name", "operator": "!=", "value": "errorChannel" }
     ]
    }
   ]
  },
  {
   "title": "($stream/$application) Channel Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 3, "y": 36 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "result" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "spring_integration_send",
     "query": "SELECT \"count\"  / 60 FROM \"spring_integration_send\" WHERE (\"stream_name\" =~ /^$stream$/ AND \"type\" = 'channel' AND \"application_name\" =~ /^$application$/ AND \"result\" = 'success' AND ( \"name\" = 'output' OR \"name\" = 'input')) AND $timeFilter GROUP BY \"application_name\", \"result\", \"application_name\", \"name\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "channel" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "output" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "input" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "success" }
     ]
    }
   ]
  },
  {
   "title": "($stream/$application) Channel Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "result" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "spring_integration_send",
     "query": "SELECT \"mean\" FROM \"spring_integration_send\" WHERE (\"stream_name\" =~ /^$stream$/ AND \"application_name\" =~ /^$application$/ AND \"type\" = 'channel' AND \"result\" = 'success' AND ( \"name\" = 'output' OR \"name\" = 'input')) AND $timeFilter GROUP BY \"stream_name\", \"application_name\", \"result\", \"name\"",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "channel" }
     ]
    }
   ]
  },
  {
   "title": "Channels ($stream / $application)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 }
  },
  {
   "title": "Throughput",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 44 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "spring_integration_send",
     "query": "SELECT count(\"count\")  / 60 FROM \"spring_integration_send\" WHERE (\"stream_name\" =~ /^$stream$/ AND \"type\" = 'channel' AND \"application_name\" =~ /^$application$/ AND \"result\" = 'success' AND ( \"name\" = 'output' OR \"name\" = 'input')) AND $timeFilter GROUP BY \"application_name\", \"result\", \"application_name\", \"name\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "name", "operator": "!=", "value": "errorChannel" }
     ]
    }
   ]
  },
  {
   "title": "($stream/$application) Channel Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 3, "y": 44 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "result" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "spring_integration_send",
     "query": "SELECT \"count\"  / 60 FROM \"spring_integration_send\" WHERE (\"stream_name\" =~ /^$stream$/ AND \"type\" = 'channel' AND \"application_name\" =~ /^$application$/ AND \"result\" = 'success' AND ( \"name\" = 'output' OR \"name\" = 'input')) AND $timeFilter GROUP BY \"application_name\", \"result\", \"application_name\", \"name\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "channel" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "output" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "input" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "success" }
     ]
    }
   ]
  },
  {
   "title": "($stream/$application) Channel Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "result" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "spring_integration_send",
     "query": "SELECT \"mean\" FROM \"spring_integration_send\" WHERE (\"stream_name\" =~ /^$stream$/ AND \"application_name\" =~ /^$application$/ AND \"type\" = 'channel' AND \"result\" = 'success' AND ( \"name\" = 'output' OR \"name\" = 'input')) AND $timeFilter GROUP BY \"stream_name\", \"application_name\", \"result\", \"name\"",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "channel" }
     ]
    }
   ]
  },
  {
   "title": "Handlers ($stream / $application)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "repeat": "application"
  },
  {
   "title": "($stream/$application) Handler Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "result" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "spring_integration_send",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "handler" },
      {
       "condition": "AND",
       "key": "name",
       "operator": "!=",
       "value": "org_springframework_cloud_stream_app_log_sink_LogSinkConfiguration_logSinkHandler_serviceActivator_handler"
      }
     ]
    }
   ]
  },
  {
   "title": "($stream/$application) Handlers Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "result" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "spring_integration_send",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "handler" },
      {
       "condition": "AND",
       "key": "name",
       "operator": "!=",
       "value": "org_springframework_cloud_stream_app_log_sink_LogSinkConfiguration_logSinkHandler_serviceActivator_handler"
      }
     ]
    }
   ]
  },
  {
   "title": "Handlers ($stream / $application)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 }
  },
  {
   "title": "($stream/$application) Handler Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "result" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "spring_integration_send",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "handler" },
      {
       "condition": "AND",
       "key": "name",
       "operator": "!=",
       "value": "org_springframework_cloud_stream_app_log_sink_LogSinkConfiguration_logSinkHandler_serviceActivator_handler"
      }
     ]
    }
   ]
  },
  {
   "title": "($stream/$application) Handlers Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "result" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "spring_integration_send",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "handler" },
      {
       "condition": "AND",
       "key": "name",
       "operator": "!=",
       "value": "org_springframework_cloud_stream_app_log_sink_LogSinkConfiguration_logSinkHandler_serviceActivator_handler"
      }
     ]
    }
   ]
  },
  {
   "title": "Handlers ($stream / $application)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 }
  },
  {
   "title": "($stream/$application) Handler Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "result" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "spring_integration_send",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "handler" },
      {
       "condition": "AND",
       "key": "name",
       "operator": "!=",
       "value": "org_springframework_cloud_stream_app_log_sink_LogSinkConfiguration_logSinkHandler_serviceActivator_handler"
      }
     ]
    }
   ]
  },
  {
   "title": "($stream/$application) Handlers Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "result" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "spring_integration_send",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "handler" },
      {
       "condition": "AND",
       "key": "name",
       "operator": "!=",
       "value": "org_springframework_cloud_stream_app_log_sink_LogSinkConfiguration_logSinkHandler_serviceActivator_handler"
      }
     ]
    }
   ]
  },
  {
   "title": "Error Channels",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Channel Throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "stream_name" ], "type": "tag" },
        { "params": [ "application_name" ], "type": "tag" },
        { "params": [ "result" ], "type": "tag" }
       ],
       "measurement": "spring_integration_send",
       "query": "SELECT \"count\"  / 60 FROM \"spring_integration_send\" WHERE (\"stream_name\" =~ /^$stream$/ AND \"application_name\" =~ /^$application$/ AND \"type\" = 'channel' AND \"name\" = 'errorChannel') AND $timeFilter GROUP BY \"stream_name\", \"application_name\", \"result\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         { "params": [ " / 60" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
        { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "channel" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "errorChannel" }
       ]
      }
     ]
    },
    {
     "title": "Error Channel Average Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "stream_name" ], "type": "tag" },
        { "params": [ "application_name" ], "type": "tag" },
        { "params": [ "result" ], "type": "tag" }
       ],
       "measurement": "spring_integration_send",
       "select": [
        [
         { "params": [ "mean" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
        { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "channel" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "errorChannel" }
       ]
      }
     ]
    }
   ]
  }
 ]
}