[appendix]
[[howto]]
== "`How-to`" guides

This section provides answers to some common '`how do I do that...`' questions that often arise when people use Spring Cloud Data Flow.

If you have a specific problem that we do not cover here, you might want to check out https://stackoverflow.com/tags/spring-cloud-dataflow[stackoverflow.com] to see if someone has already provided an answer.
That is also a great place to ask new questions (use the `spring-cloud-dataflow` tag).

We are also more than happy to extend this section. If you want to add a "`how-to`", you can send us a {github-code}[pull request].

=== Configure Maven Properties
If applications are resolved by using the Maven repository you may want to configure the underlying resolver.

You can set the Maven properties, such as the local Maven repository location, remote Maven repositories, authentication credentials, and proxy server properties through command-line properties when you start the Data Flow server.
Alternatively, you can set the properties by setting the `SPRING_APPLICATION_JSON` environment property for the Data Flow server.

For all Data Flow server installations, the following list of remote Maven repositories are configured by default:

* Maven Central (`https://repo.maven.apache.org/maven2`)
* Spring Snapshots (`https://repo.spring.io/snapshot`)
* Spring Milestones (`https://repo.spring.io/milestone`)

If the default is already explicitly configured (exact match on the repo url) then it will not be included.

If the applications exist on another remote repository, besides the pre-configured ones, that remote repository must be configured explicitly and will be added to the pre-configured default list.

TIP: To skip the automatic default repositories behavior altogether, set the `maven.include-default-remote-repos` property to `false`.

To pass the properties as command-line options, run the server with a command similar to the following:

====
[source,shell]
----
java -jar <dataflow-server>.jar --maven.localRepoitory=mylocal \
--maven.remote-repositories.repo1.url=https://repo1 \
--maven.remote-repositories.repo1.auth.username=repo1user \
--maven.remote-repositories.repo1.auth.password=repo1pass \
--maven.remote-repositories.repo2.url=https://repo2 \
--maven.proxy.host=proxyhost \
--maven.proxy.port=9018 \
--maven.proxy.auth.username=proxyuser \
--maven.proxy.auth.password=proxypass
----
====

You can also use the `SPRING_APPLICATION_JSON` environment property:

====
[source,json]
----
export SPRING_APPLICATION_JSON='{ "maven": { "local-repository": "local","remote-repositories": { "repo1": { "url": "https://repo1", "auth": { "username": "repo1user", "password": "repo1pass" } },
"repo2": { "url": "https://repo2" } }, "proxy": { "host": "proxyhost", "port": 9018, "auth": { "username": "proxyuser", "password": "proxypass" } } } }'
----
====

Here is the same content in nicely formatted JSON:

====
[source,json]
----
SPRING_APPLICATION_JSON='{
  "maven": {
    "local-repository": "local",
    "remote-repositories": {
      "repo1": {
        "url": "https://repo1",
        "auth": {
          "username": "repo1user",
          "password": "repo1pass"
        }
      },
      "repo2": {
        "url": "https://repo2"
      }
    },
    "proxy": {
      "host": "proxyhost",
      "port": 9018,
      "auth": {
        "username": "proxyuser",
        "password": "proxypass"
      }
    }
  }
}'
----
====

You can also set the properties as individual environment variables:

====
[source,bash]
----
export MAVEN_REMOTEREPOSITORIES_REPO1_URL=https://repo1
export MAVEN_REMOTEREPOSITORIES_REPO1_AUTH_USERNAME=repo1user
export MAVEN_REMOTEREPOSITORIES_REPO1_AUTH_PASSWORD=repo1pass
export MAVEN_REMOTEREPOSITORIES_REPO2_URL=https://repo2
export MAVEN_PROXY_HOST=proxyhost
export MAVEN_PROXY_PORT=9018
export MAVEN_PROXY_AUTH_USERNAME=proxyuser
export MAVEN_PROXY_AUTH_PASSWORD=proxypass
----
====

=== Troubleshooting

This section covers how to troubleshoot Spring Cloud Data Flow on your platform of choice. See the Troubleshooting sections of the microsite for link:https://dataflow.spring.io/docs/stream-developer-guides/troubleshooting/[Stream] and link:https://dataflow.spring.io/docs/batch-developer-guides/troubleshooting/[Batch] processing.

include::appendix-extend-classpath.adoc[]
include::appendix-create-containers.adoc[]
include::appendix-local-k8s-development.adoc[]

[[faqs]]
=== Frequently Asked Questions

In this section, we review the frequently asked questions for Spring Cloud Data Flow.
See the https://dataflow.spring.io/docs/resources/faq/[Frequently Asked Questions] section of the microsite for more information.

// TODO move the FAQ to reference guide.
