[appendix]
[[building]]
== Building

This appendix describes how to build Spring Cloud Data Flow.

To build the source, you need to install JDK 1.8.

The build uses the Maven wrapper so that you do not have to install a specific version of Maven.

The main build command is as follows:

====
[source,bash]
----
$ ./mvnw clean install
----
====

To speed up the build, you can add `-DskipTests` to avoid running the tests.

NOTE: You can also install Maven (>=3.3.3) yourself and run the `mvn` command in place of `./mvnw` in the examples below.
If you do that, you also might need to add `-P spring` if your local Maven settings do not contain repository declarations for Spring pre-release artifacts.

NOTE: You might need to increase the amount of memory available to Maven by setting a `MAVEN_OPTS` environment variable with a value similar to `-Xmx512m -XX:MaxPermSize=128m`.
We try to cover this in the `.mvn` configuration, so, if you find you have to do it to make a build succeed, please raise a ticket to get the settings added to source control.

=== Documentation

There is a `full` profile that generates documentation. You can build only the documentation by using the following command:

====
[source,bash]
----
$ ./mvnw clean package -DskipTests -P full -pl {project-artifactId} -am
----
====

=== Working with the Code

If you do not have a favorite IDE, we recommend that you use https://spring.io/tools[Spring Tools Suite] or https://www.eclipse.org[Eclipse] when working with the code.
We use the https://www.eclipse.org/m2e/[m2eclipse] Eclipse plugin for Maven support.
Other IDEs and tools generally also work without issue.



==== Importing into Eclipse with m2eclipse

We recommend the https://www.eclipse.org/m2e/[m2eclipe] eclipse plugin when working with Eclipse.
If you do not already have m2eclipse installed, it is available from the Eclipse marketplace.

Unfortunately, m2e does not yet support Maven 3.3.
Consequently, once the projects are imported into Eclipse, you also need to tell m2eclipse to use the `.settings.xml` file for the projects.
If you do not do this, you may see many different errors related to the POMs in the projects.
To do so:

. Open your Eclipse preferences.
. Expand the *Maven preferences*.
. Select *User Settings*.
. In the *User Settings* field, click *Browse* and navigate to the Spring Cloud project you imported.
. Select the `.settings.xml` file in that project.
. Click *Apply*.
. Click *OK*.

NOTE: Alternatively, you can copy the repository settings from Spring Cloud's https://github.com/spring-cloud/spring-cloud-build/blob/master/.settings.xml[`.settings.xml`] file into your own `~/.m2/settings.xml`.



==== Importing into Eclipse without m2eclipse

If you prefer not to use m2eclipse, you can generate Eclipse project metadata by using the following command:

====
[source,bash]
----
$ ./mvnw eclipse:eclipse
----
====

You can import the generated Eclipse projects by selecting *Import existing projects*
from the *File* menu.
