[[configuration]]
= Configuration

[[configuration-maven]]
== Maven
If you want to override specific maven configuration properties (remote repositories, proxies, and others) or run the Data Flow Server behind a proxy,
you need to specify those properties as command line arguments when starting the Data Flow Server, as shown in the following example:

[source,bash,subs=attributes]
----
$ java -jar spring-cloud-dataflow-server-{project-version}.jar --spring.config.additional-location=/home/joe/maven.yml
----

where `maven.yaml` is

[source,yml]
----
maven:
  localRepository: mylocal
  remote-repositories:
    repo1:
      url: https://repo1
      auth:
        username: user1
        password: pass1
      snapshot-policy:
        update-policy: daily
        checksum-policy: warn
      release-policy:
        update-policy: never
        checksum-policy: fail
    repo2:
      url: https://repo2
      policy:
        update-policy: always
        checksum-policy: fail
  proxy:
    host: proxy1
    port: "9010"
    auth:
      username: proxyuser1
      password: proxypass1
----



By default, the protocol is set to `http`. You can omit the auth properties if the proxy does not need a username and password. Also, the maven `localRepository` is set to `${user.home}/.m2/repository/` by default.
As shown in the preceding example, the remote repositories can be specified along with their authentication (if needed). If the remote repositories are behind a proxy, then the proxy properties can be specified as shown in the preceding example.

The repository policies can be specified for each remote repository configuration as shown in the preceding example.
The key `policy` is applicable to both `snapshot` and the `release` repository policies.

You can refer to https://github.com/apache/maven-resolver/blob/master/maven-resolver-api/src/main/java/org/eclipse/aether/repository/RepositoryPolicy.java[Repository Policies] for the list of
supported repository policies.

As these are Spring Boot `@ConfigurationProperties`, that you need to specify by adding them to the `SPRING_APPLICATION_JSON` environment variable. The following example shows how the JSON is structured:

[source,bash,subs=attributes]
----
$ SPRING_APPLICATION_JSON='
{
  "maven": {
    "local-repository": null,
    "remote-repositories": {
      "repo1": {
        "url": "https://repo1",
        "auth": {
          "username": "repo1user",
          "password": "repo1pass"
        }
      },
      "repo2": {
        "url": "https://repo2"
      }
    },
    "proxy": {
      "host": "proxyhost",
      "port": 9018,
      "auth": {
        "username": "proxyuser",
        "password": "proxypass"
      }
    }
  }
}
'
----

=== Wagon
There is a limited support for using `Wagon` transport with maven. Currently this
exists to support _preemptive_ authentication with `http` based repositories
and needs to be enabled manually.

Wagon based http transport is enabled by setting `maven.use-wagon` property
to `true` and then _preemptive_ authentication can be enabled per remote
repository. Configuration loosely follows similar patterns found in
https://maven.apache.org/guides/mini/guide-http-settings.html[HttpClient HTTP Wagon].
At a time of writing this, documentation in Maven's own site is slightly misleading
and missing most of the possible config options.

Namespace `maven.remote-repositories.<repo>.wagon.http` contains all Wagon
http related settings and keys directly under it maps to supported http methods,
namely `all`, `put`, `get` and `head` just like in Maven's own configuration.
Under these method configurations you can then set various options like
`use-preemptive`. Most simplest _preemptive_ configuration sending auth
header with all requests to a specified remote repository would look like:

[source,yml]
----
maven:
  use-wagon: true
  remote-repositories:
    springRepo:
      url: https://repo.example.org
      wagon:
        http:
          all:
            use-preemptive: true
      auth:
        username: user
        password: password
----

Instead of configuring `all` methods it's possible to tune settings for `get`
and `head` requests only:

[source,yml]
----
maven:
  use-wagon: true
  remote-repositories:
    springRepo:
      url: https://repo.example.org
      wagon:
        http:
          get:
            use-preemptive: true
          head:
            use-preemptive: true
            use-default-headers: true
            connection-timeout: 1000
            read-timeout: 1000
            headers:
              Foo: Bar
            params:
              http.socket.timeout: 1000
              http.connection.stalecheck: true
      auth:
        username: user
        password: password
----

There are settings for `use-default-headers`, `connection-timeout`,
`read-timeout`, request `headers` and HttpClient `params`. More about params
check https://github.com/apache/maven-wagon/blob/master/wagon-providers/wagon-http-shared/src/main/java/org/apache/maven/wagon/shared/http/ConfigurationUtils.java[Wagon ConfigurationUtils].

include::configuration-local.adoc[]
include::configuration-cloudfoundry.adoc[]
include::configuration-kubernetes.adoc[]
