[[getting-started]]
= Getting started

[partintro]
--
If you're just getting started with Spring Cloud Data Flow, this is the section
for you! Here we answer the basic "`what?`", "`how?`" and "`why?`" questions. You'll
find a gentle introduction to Spring Cloud Data Flow along with installation instructions.
We'll then build our first Spring Cloud Data Flow application, discussing some core principles as
we go.
--

[[getting-started-system-requirements]]
== System Requirements

You need Java installed (Java 7 or better, we recommend Java 8), and to build, you need to have Maven installed as well.

You also need to have link:http://redis.io/[Redis] installed and running if you plan on running a local system, or to run the included tests.

[[getting-started-deploying-spring-cloud-dataflow]]
== Deploying Spring Cloud Data Flow

=== Deploying 'local'
. Download the Spring Cloud Data Flow Server and Shell apps:
+
[source,bash,subs=attributes]
----
wget http://repo.spring.io/milestone/org/springframework/cloud/spring-cloud-dataflow-server-local/{project-version}/spring-cloud-dataflow-server-local-{project-version}.jar

wget http://repo.spring.io/milestone/org/springframework/cloud/spring-cloud-dataflow-shell/{project-version}/spring-cloud-dataflow-shell-{project-version}.jar
----
+
. Launch the Data Flow Server
+
.. Since the Data Flow Server is a Spring Boot application, you can run it just by using `java -jar`.
+
[source,bash,subs=attributes]
----
$ java -jar spring-cloud-dataflow-server-local-{project-version}.jar
----
+
.. Running with Custom Maven Settings and/or Behind a Proxy
If you want to override specific maven configuration properties (remote repositories, etc.) and/or run the Data Flow Server behind a proxy,
you need to specify those properties as command line arguments when starting the Data Flow Server. For example:
+
[source,bash,subs=attributes]
----
$ java -jar spring-cloud-dataflow-server-local-{project-version}.jar --maven.localRepository=mylocal --maven.remoteRepositories=repo1,repo2 --maven.offline=true
--maven.proxy.protocol=https --maven.proxy.host=host1 --maven.proxy.port=8090 --maven.proxy.non_proxy_hosts='host2|host3' --maven.proxy.auth.username=user1 --maven.proxy.auth.password=passwd
----
+
By default, the protocol is set to `http`. You can omit the auth properties if the proxy doesn't need a username and password.
+
By default, the maven `localRepository` is set to `${user.home}/.m2/repository/`,
and `https://repo.spring.io/libs-snapshot` will be the only remote repository.
+
You can also use environment variables to specify the maven/proxy properties:
+
[source,bash]
----
export MAVEN_LOCAL_REPOSITORY=mylocalMavenRepo
export MAVEN_REMOTE_REPOSITORIES=repo1,repo2
export MAVEN_OFFLINE=true
export MAVEN_PROXY_PROTOCOL=https
export MAVEN_PROXY_HOST=host1
export MAVEN_PROXY_PORT=8090
export MAVEN_PROXY_NON_PROXY_HOSTS='host2|host3'
export MAVEN_PROXY_AUTH_USERNAME=user1
export MAVEN_PROXY_AUTH_PASSWORD=passwd
----
+
. Launch the shell:
+
[source,bash,subs=attributes]
----
$ java -jar spring-cloud-dataflow-shell-{project-version}.jar
----
+
If the Data Flow Server and shell are not running on the same host, point the shell to the Data Flow server:
+
[source,bash]
----
server-unknown:>dataflow config server http://dataflow-server.cfapps.io
Successfully targeted http://dataflow-server.cfapps.io
dataflow:>
----
+
. You can now use the shell commands to list available applications (source/processors/sink) and create streams. For example:
+
[source,bash]
----
dataflow:> stream create --name httptest --definition "http --server.port=9000 | log" --deploy
----
+
NOTE: You will need to wait a little while until the apps are actually deployed successfully
before posting data.  Look in the log file of the Data Flow server for the location of the log
files for the `http` and `log` applications.  Tail the log file for each application to verify
the application has started.
+
Now post some data
[source,bash]
----
dataflow:> http post --target http://localhost:9000 --data "hello world"
----
Look to see if `hello world` ended up in log files for the `log` application.

[[getting-started-security]]
== Security

By default, the Dataflow server is unsecured and runs on an unencrypted HTTP connection.
You can secure your REST endpoints, as well as the Dataflow Dashboard by enabling HTTPS
and requiring clients to authenticate.

[[getting-started-security-enabling-https]]
=== Enabling HTTPS

By default, the dashboard, management, and health endpoints use HTTP as a transport.
You can switch to HTTPS easily, by adding a certificate to your configuration in
`application.yml`.

[source,yaml]
----
server:
  port: 8443                                         # <1>
  ssl:
    key-alias: yourKeyAlias                          # <2>
    key-store: path/to/keystore                      # <3>
    key-store-password: yourKeyStorePassword         # <4>
    key-password: yourKeyPassword                    # <5>
    trust-store: path/to/trust-store                 # <6>
    trust-store-password: yourTrustStorePassword     # <7>
----

<1> As the default port is `9393`, you may choose to change the port to a more common HTTPs-typical port.
<2> The alias (or name) under which the key is stored in the keystore.
<3> The path to the keystore file. Classpath resources may also be specified, by using the classpath prefix: `classpath:path/to/keystore`
<4> The password of the keystore.
<5> The password of the key.
<6> The path to the truststore file. Classpath resources may also be specified, by using the classpath prefix: `classpath:path/to/trust-store`
<7> The password of the trust store.

NOTE: If HTTPS is enabled, it will completely replace HTTP as the protocol over
which the REST endpoints and the Dataflow Dashboard interact. Plain HTTP requests
will fail - therefore, make sure that you configure your Shell accordingly.

==== Using Self-Signed Certificates

For testing purposes or during development it might be convenient to create self-signed certificates.
To get started, execute the following command to create a certificate:

[source,bash]
----
$ keytool -genkey -alias dataflow -keyalg RSA -keystore dataflow.keystore \
          -validity 3650 -storetype JKS \
          -dname "CN=localhost, OU=Spring, O=Pivotal, L=Kailua-Kona, ST=HI, C=US"  # <1>
          -keypass dataflow -storepass dataflow
----

<1> _CN_ is the only important parameter here. It should match the domain you are trying to access, e.g. `localhost`.

Then add the following to your `application.yml` file:

[source,yaml]
----
server:
  port: 8443
  ssl:
    enabled: true
    key-alias: dataflow
    key-store: "/your/path/to/dataflow.keystore"
    key-store-type: jks
    key-store-password: dataflow
    key-password: dataflow
----

This is all that's needed for the Dataflow Server. Once you start the server,
you should be able to access it via https://localhost:8443/[https://localhost:8443/]. As this is a self-signed
certificate, you will hit a warning in your browser, that you need to ignore.

This issue also is relevant for the Dataflow Shell. Therefore additional steps are
necessary to make the Shell work with self-signed certificates. First, we need to
export the previously created certificate from the keystore:

[source,bash]
----
$ keytool -export -alias dataflow -keystore dataflow.keystore -file dataflow_cert -storepass dataflow
----

Next, we need to create a truststore which the Shell will use:

[source,bash]
----
$ keytool -importcert -keystore dataflow.truststore -alias dataflow -storepass dataflow -file dataflow_cert -noprompt
----

Now, you are ready to launch the Dataflow Shell using the following JVM arguments:

[source,bash,subs=attributes]
----
$ java -Djavax.net.ssl.trustStorePassword=dataflow \
       -Djavax.net.ssl.trustStore=/path/to/dataflow.truststore \
       -Djavax.net.ssl.trustStoreType=jks \
       -jar spring-cloud-dataflow-shell-{project-version}.jar
----

[TIP]
====
In case you run into trouble establishing a connection via SSL, you can enable additional
logging by using and setting the `javax.net.debug` JVM argument to `ssl`.
====

Don't forget to target the Dataflow Server with:

[source,bash]
----
dataflow:> dataflow config server https://localhost:8443/
----

[[getting-started-security-enabling-authentication]]
=== Enabling Authentication

By default, the REST endpoints (administration, management and health), as well
as Dashboard UI do not require authenticated access. However, authentication can
be provided via http://oauth.net/2/[OAuth 2.0], thus allowing you to also integrate Spring Cloud
Data Flow into Single Sign On (SSO) environments. The following 2 OAuth2 Grant Types will be used:

* _Authorization Code_ - Used for the GUI (Browser) integration. You will be redirected to your OAuth Service for authentication
* _Password_ - Used by the shell (And the REST integration), so you can login using username and password

The REST endpoints are secured via Basic Authentication but will use the Password
Grand Type under the covers to authenticate with your OAuth2 service.

NOTE: When authentication is set up, it is strongly recommended to enable HTTPS
as well, especially in production environments.

You can turn on authentication by adding the following to `application.yml` or via
environment variables:

[source,yaml]
----
security:
  basic:
    enabled: true                                                     # <1>
    realm: Spring Cloud Data Flow                                     # <2>
  oauth2:                                                             # <3>
    client:
      client-id: myclient
      client-secret: mysecret
      access-token-uri: http://127.0.0.1:9999/oauth/token
      user-authorization-uri: http://127.0.0.1:9999/oauth/authorize
    resource:
      user-info-uri: http://127.0.0.1:9999/me
----

<1> Must be set to `true` for security to be enabled.
<2> The realm for Basic authentication
<3> OAuth Configuration Section

NOTE: As of version 1.0 Spring Cloud Dataflow does not provide finer-grained authorization. Thus, once you are logged in, you have full access to all functionality.

You can verify that basic authentication is working properly using _curl_:

[source,bash]
----
$ curl -u myusername:mypassword http://localhost:9393/
----

As a result you should see a list of available REST endpoints.

[[getting-started-security-enabling-authentication-cloud-foundry]]
==== Authentication and Cloud Foundry

When deploying Spring Cloud Data Flow to Cloud Foundry, we take advantage of the
https://github.com/pivotal-cf/spring-cloud-sso-connector[_Spring Cloud Single Sign-On Connector_],
which provides Cloud Foundry specific auto-configuration support for OAuth 2.0
when used in conjunction with the _Pivotal Single Sign-On Service_.

Simply set `security.basic.enabled` to `true` and in Cloud Foundry bind the SSO
service to your Dataflow Server app and SSO will be enabled.

