[[getting-started-kubernetes]]
== Getting Started - Kubernetes

https://cloud.spring.io/spring-cloud-dataflow/[Spring Cloud Data Flow] is a toolkit for building data integration and real-time data-processing pipelines.

Pipelines consist of Spring Boot apps, built with the Spring Cloud Stream or Spring Cloud Task microservice frameworks.
This makes Spring Cloud Data Flow suitable for a range of data-processing use cases, from import-export to event-streaming and predictive analytics.

This project provides support for using Spring Cloud Data Flow with Kubernetes as the runtime for these pipelines, with applications packaged as Docker images.

Please see the link:https://dataflow.spring.io/docs/installation/kubernetes/[Kubernetes] section of the microsite for more information on installing Spring Cloud Data Flow on Kubernetes.

Once you have the Data Flow server installed on Kubernetes, you will want to get started with orchestrating the deployment of readily available pre-built applications into a coherent streaming or batch data pipelines. Below we have guides on how to get started with both link:https://dataflow.spring.io/docs/stream-developer-guides/[Stream] and link:https://dataflow.spring.io/docs/batch-developer-guides/[Batch] processing.

=== Application and Server Properties

This section covers how you can customize the deployment of your applications. You can use a number of properties to influence settings for the applications that are deployed. Properties can be applied on a per-application basis or in the appropriate server configuration for all deployed applications.

NOTE: Properties set on a per-application basis always take precedence over properties set as the server configuration. This arrangement lets you override global server level properties on a per-application basis.

Properties to be applied for all deployed Tasks are defined in the `src/kubernetes/server/server-config-(binder).yaml` file and for Streams in `src/kubernetes/skipper/skipper-config-(binder).yaml`. Replace `(binder)` with the messaging middleware you are using -- for example, `rabbit` or `kafka`.

==== Memory and CPU Settings

Applications are deployed with default memory and CPU settings. If needed, these values can be adjusted. The following example shows how to set `Limits` to `1000m` for `CPU` and `1024Mi` for memory and `Requests` to `800m` for CPU and `640Mi` for memory:

====
[source]
----
deployer.<app>.kubernetes.limits.cpu=1000m
deployer.<app>.kubernetes.limits.memory=1024Mi
deployer.<app>.kubernetes.requests.cpu=800m
deployer.<app>.kubernetes.requests.memory=640Mi
----
====

Those values results in the following container settings being used:

====
[source]
----
Limits:
  cpu:	1
  memory:	1Gi
Requests:
  cpu:	800m
  memory:	640Mi
----
====

You can also control the default values to which to set the `cpu` and `memory` globally.

The following example shows how to set the CPU and memory for streams:

====
[source,yaml]
----
data:
  application.yaml: |-
    spring:
      cloud:
        skipper:
          server:
            platform:
              kubernetes:
                accounts:
                  default:
                    limits:
                      memory: 640mi
                      cpu: 500m
----
====

The following example shows how to set the CPU and memory for tasks:

====
[source,yaml]
----
data:
  application.yaml: |-
    spring:
      cloud:
        dataflow:
          task:
            platform:
              kubernetes:
                accounts:
                  default:
                    limits:
                      memory: 640mi
                      cpu: 500m
----
====

The settings we have used so far only affect the settings for the container. They do not affect the memory setting for the JVM process in the container. If you would like to set JVM memory settings, you can provide an environment variable to do so. See the next section for details.

==== Environment Variables

To influence the environment settings for a given application, you can use the `spring.cloud.deployer.kubernetes.environmentVariables` deployer property.
For example, a common requirement in production settings is to influence the JVM memory arguments.
You can do so by using the `JAVA_TOOL_OPTIONS` environment variable, as the following example shows:

====
[source]
----
deployer.<app>.kubernetes.environmentVariables=JAVA_TOOL_OPTIONS=-Xmx1024m
----
====

NOTE: The `environmentVariables` property accepts a comma-delimited string. If an environment variable contains a value
which is also a comma-delimited string, it must be enclosed in single quotation marks -- for example,
`spring.cloud.deployer.kubernetes.environmentVariables=spring.cloud.stream.kafka.binder.brokers='somehost:9092,
anotherhost:9093'`

This overrides the JVM memory setting for the desired `<app>` (replace `<app>` with the name of your application).

[[getting-started-kubernetes-probes]]
==== Liveness and Readiness Probes

The `liveness` and `readiness` probes use paths called `/health` and `/info`, respectively. They use a `delay` of `10` for both and a `period` of `60` and `10` respectively. You can change these defaults when you deploy the stream by using deployer properties. Liveness and readiness probes are only applied to streams.

The following example changes the `liveness` probe (replace `<app>` with the name of your application) by setting deployer properties:

====
[source]
----
deployer.<app>.kubernetes.livenessProbePath=/health
deployer.<app>.kubernetes.livenessProbeDelay=120
deployer.<app>.kubernetes.livenessProbePeriod=20
----
====

You can declare the same as part of the server global configuration for streams, as the following example shows:

====
[source,yaml]
----
data:
  application.yaml: |-
    spring:
      cloud:
        skipper:
          server:
            platform:
              kubernetes:
                accounts:
                  default:
                    livenessProbePath: /health
                    livenessProbeDelay: 120
                    livenessProbePeriod: 20
----
====

Similarly, you can swap `liveness` for `readiness` to override the default `readiness` settings.

By default, port 8080 is used as the probe port. You can change the defaults for both `liveness` and `readiness` probe ports by using deployer properties, as the following example shows:

====
[source]
----
deployer.<app>.kubernetes.readinessProbePort=7000
deployer.<app>.kubernetes.livenessProbePort=7000
----
====

You can declare the same as part of the global configuration for streams, as the following example shows:

====
[source,yaml]
----
data:
  application.yaml: |-
    spring:
      cloud:
        skipper:
          server:
            platform:
              kubernetes:
                accounts:
                  default:
                    readinessProbePort: 7000
                    livenessProbePort: 7000
----
====

[NOTE]
=====
By default, the `liveness` and `readiness` probe paths use Spring Boot 2.x+ actuator endpoints. To use Spring Boot 1.x actuator endpoint paths, you must adjust the `liveness` and `readiness` values, as the following example shows (replace `<app>` with the name of your application):

====
[source]
----
deployer.<app>.kubernetes.livenessProbePath=/health
deployer.<app>.kubernetes.readinessProbePath=/info
----
====

To automatically set both `liveness` and `readiness` endpoints on a per-application basis to the default Spring Boot 1.x paths, you can set the following property:

====
[source]
----
deployer.<app>.kubernetes.bootMajorVersion=1
----
====

=====

You can access secured probe endpoints by using credentials stored in a https://kubernetes.io/docs/concepts/configuration/secret/[Kubernetes secret]. You can use an existing secret, provided the credentials are contained under the `credentials` key name of the secret's `data` block. You can configure probe authentication on a per-application basis. When enabled, it is applied to both the `liveness` and `readiness` probe endpoints by using the same credentials and authentication type. Currently, only `Basic` authentication is supported.

To create a new secret:

. Generate the base64 string with the credentials used to access the secured probe endpoints.
+
Basic authentication encodes a username and password as a base64 string in the format of `username:password`.
+
The following example (which includes output and in which you should replace `user` and `pass` with your values) shows how to generate a base64 string:
+
====
[source,shell]
----
$ echo -n "user:pass" | base64
dXNlcjpwYXNz
----
====

. With the encoded credentials, create a file (for example, `myprobesecret.yml`) with the following contents:
+
====
[source]
----
apiVersion: v1
kind: Secret
metadata:
  name: myprobesecret
type: Opaque
data:
  credentials: GENERATED_BASE64_STRING
----
====

. Replace `GENERATED_BASE64_STRING` with the base64-encoded value generated earlier.

. Create the secret by using `kubectl`, as the following example shows:
+
====
[source,shell]
----
$ kubectl create -f ./myprobesecret.yml
secret "myprobesecret" created
----
====

. Set the following deployer properties to use authentication when accessing probe endpoints, as the following example shows:
+
====
[source]
----
deployer.<app>.kubernetes.probeCredentialsSecret=myprobesecret
----
====
+
Replace `<app>` with the name of the application to which to apply authentication.

==== Using `SPRING_APPLICATION_JSON`

You can use a `SPRING_APPLICATION_JSON` environment variable to set Data Flow server properties (including the configuration of maven repository settings) that are common across all of the Data Flow server implementations. These settings go at the server level in the container `env` section of a deployment YAML. The following example shows how to do so:

====
[source,options=nowrap]
----
env:
- name: SPRING_APPLICATION_JSON
  value: "{ \"maven\": { \"local-repository\": null, \"remote-repositories\": { \"repo1\": { \"url\": \"https://repo.spring.io/libs-snapshot\"} } } }"
----
====

==== Private Docker Registry

You can pull Docker images from a private registry on a per-application basis. First, you must create a secret in the cluster. Follow the https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/[Pull an Image from a Private Registry] guide to create the secret.

Once you have created the secret, you can use the `imagePullSecret` property to set the secret to use, as the following example shows:

====
[source]
----
deployer.<app>.kubernetes.imagePullSecret=mysecret
----
====

Replace `<app>` with the name of your application and `mysecret` with the name of the secret you created earlier.

You can also configure the image pull secret at the global server level.

The following example shows how to do so for streams:

====
[source,yaml]
----
data:
  application.yaml: |-
    spring:
      cloud:
        skipper:
          server:
            platform:
              kubernetes:
                accounts:
                  default:
                    imagePullSecret: mysecret
----
====

The following example shows how to do so for tasks:

====
[source,yaml]
----
data:
  application.yaml: |-
    spring:
      cloud:
        dataflow:
          task:
            platform:
              kubernetes:
                accounts:
                  default:
                    imagePullSecret: mysecret
----
====

Replace `mysecret` with the name of the secret you created earlier.

==== Annotations

You can add annotations to Kubernetes objects on a per-application basis. The supported object types are pod `Deployment`, `Service`, and `Job`. Annotations are defined in a `key:value` format, allowing for multiple annotations separated by a comma. For more information and use cases on annotations, see https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/[Annotations].

The following example shows how you can configure applications to use annotations:

====
[source,options=nowrap]
----
deployer.<app>.kubernetes.podAnnotations=annotationName:annotationValue
deployer.<app>.kubernetes.serviceAnnotations=annotationName:annotationValue,annotationName2:annotationValue2
deployer.<app>.kubernetes.jobAnnotations=annotationName:annotationValue
----
====

Replace `<app>` with the name of your application and the value of your annotations.

==== Entry Point Style

An entry point style affects how application properties are passed to the container to be deployed. Currently, three styles are supported:

* `exec` (default): Passes all application properties and command line arguments in the deployment request as container arguments. Application properties are transformed into the format of `--key=value`.
* `shell`: Passes all application properties as environment variables. Command line arguments from the deployment request are not converted into environment variables nor set on the container. Application properties are transformed into an uppercase string and `.` characters are replaced with `_`.
* `boot`: Creates an environment variable called `SPRING_APPLICATION_JSON` that contains a JSON representation of all application properties. Command line arguments from the deployment request are set as container args.

NOTE: In all cases, environment variables defined at the server-level configuration and on a per-application basis are set onto the container as is.

You can configure applications as follows:

====
[source,options=nowrap]
----
deployer.<app>.kubernetes.entryPointStyle=<Entry Point Style>
----
====

Replace `<app>` with the name of your application and `<Entry Point Style>` with your desired entry point style.

You can also configure the entry point style at the global server level.

The following example shows how to do so for streams:

====
[source,yaml]
----
data:
  application.yaml: |-
    spring:
      cloud:
        skipper:
          server:
            platform:
              kubernetes:
                accounts:
                  default:
                    entryPointStyle: entryPointStyle
----
====

The following example shows how to do so for tasks:

====
[source,yaml]
----
data:
  application.yaml: |-
    spring:
      cloud:
        dataflow:
          task:
            platform:
              kubernetes:
                accounts:
                  default:
                    entryPointStyle: entryPointStyle
----
====

Replace `entryPointStye` with the desired entry point style.

You should choose an Entry Point Style of either `exec` or `shell`, to correspond to how the `ENTRYPOINT` syntax is defined in the container's `Dockerfile`. For more information and uses cases on `exec` versus `shell`, see the https://docs.docker.com/engine/reference/builder/#entrypoint[ENTRYPOINT] section of the Docker documentation.

Using the `boot` entry point style corresponds to using the `exec` style `ENTRYPOINT`. Command line arguments from the deployment request are passed to the container, with the addition of application properties being mapped into the `SPRING_APPLICATION_JSON` environment variable rather than command line arguments.

NOTE: When you use the `boot` Entry Point Style, the `deployer.<app>.kubernetes.environmentVariables` property must not contain `SPRING_APPLICATION_JSON`.

==== Deployment Service Account

You can configure a custom service account for application deployments through properties. You can use an existing service account or create a new one. One way to create a service account is by using `kubectl`, as the following example shows:

====
[source,shell]
----
$ kubectl create serviceaccount myserviceaccountname
serviceaccount "myserviceaccountname" created
----
====

Then you can configure individual applications as follows:

====
[source,options=nowrap]
----
deployer.<app>.kubernetes.deploymentServiceAccountName=myserviceaccountname
----
====

Replace `<app>` with the name of your application and `myserviceaccountname` with your service account name.

You can also configure the service account name at the global server level.

The following example shows how to do so for streams:

====
[source,yaml]
----
data:
  application.yaml: |-
    spring:
      cloud:
        skipper:
          server:
            platform:
              kubernetes:
                accounts:
                  default:
                    deploymentServiceAccountName: myserviceaccountname
----
====

The following example shows how to do so for tasks:

====
[source,yaml]
----
data:
  application.yaml: |-
    spring:
      cloud:
        dataflow:
          task:
            platform:
              kubernetes:
                accounts:
                  default:
                    deploymentServiceAccountName: myserviceaccountname
----
====

Replace `myserviceaccountname` with the service account name to be applied to all deployments.

==== Image Pull Policy

An image pull policy defines when a Docker image should be pulled to the local registry. Currently, three policies are supported:

* `IfNotPresent` (default): Do not pull an image if it already exists.
* `Always`: Always pull the image regardless of whether it already exists.
* `Never`: Never pull an image. Use only an image that already exists.

The following example shows how you can individually configure applications:

====
[source,options=nowrap]
----
deployer.<app>.kubernetes.imagePullPolicy=Always
----
====

Replace `<app>` with the name of your application and `Always` with your desired image pull policy.

You can configure an image pull policy at the global server level.

The following example shows how to do so for streams:

====
[source,yaml]
----
data:
  application.yaml: |-
    spring:
      cloud:
        skipper:
          server:
            platform:
              kubernetes:
                accounts:
                  default:
                    imagePullPolicy: Always
----
====

The following example shows how to do so for tasks:

====
[source,yaml]
----
data:
  application.yaml: |-
    spring:
      cloud:
        dataflow:
          task:
            platform:
              kubernetes:
                accounts:
                  default:
                    imagePullPolicy: Always
----
====

Replace `Always` with your desired image pull policy.

==== Deployment Labels

You can set custom labels on objects related to https://kubernetes.io/docs/concepts/workloads/controllers/deployment/[Deployment]. See https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/[Labels] for more information on labels. Labels are specified in `key:value` format.

The following example shows how you can individually configure applications:

====
[source,options=nowrap]
----
deployer.<app>.kubernetes.deploymentLabels=myLabelName:myLabelValue
----
====

Replace `<app>` with the name of your application, `myLabelName` with your label name, and `myLabelValue` with the value of your label.

Additionally, you can apply multiple labels, as the following example shows:

====
[source,options=nowrap]
----
deployer.<app>.kubernetes.deploymentLabels=myLabelName:myLabelValue,myLabelName2:myLabelValue2
----
====

==== Tolerations

Tolerations work with taints to ensure pods are not scheduled onto particular nodes.
Tolerations are set into the pod configuration while taints are set onto nodes.
Refer to the https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/[Taints and Tolerations] section of the Kubernetes reference for more information.

The following example shows how you can individually configure applications:

====
[source,options=nowrap]
----
deployer.<app>.kubernetes.tolerations=[{key: 'mykey' operator: 'Equal', value: 'myvalue', effect: 'NoSchedule'}]
----
====

Replace `<app>` with the name of your application and the key / value pairs according to your desired toleration configuration.

You can configure tolerations at the global server level as well.

The following example shows how to do so for streams:

====
[source,yaml]
----
data:
  application.yaml: |-
    spring:
      cloud:
        skipper:
          server:
            platform:
              kubernetes:
                accounts:
                  default:
                    tolerations:
                      - key: mykey
                        operator: Equal
                        value: myvalue
                        effect: NoSchedule
----
====

The following example shows how to do so for tasks:

====
[source,yaml]
----
data:
  application.yaml: |-
    spring:
      cloud:
        dataflow:
          task:
            platform:
              kubernetes:
                accounts:
                  default:
                    tolerations:
                      - key: mykey
                        operator: Equal
                        value: myvalue
                        effect: NoSchedule
----
====

Replacing the `tolerations` key / value pairs according to your desired toleration configuration.
