[[preface]]
= Preface

[[dataflow-documentation-about]]
== About the documentation
The documentation for this release is available in {spring-cloud-dataflow-docs}/htmlsingle[HTML].

The latest copy of the Spring Cloud Data Flow reference guide can be found {spring-cloud-dataflow-docs-current}[here].

Copies of this document may be made for your own use and for
distribution to others, provided that you do not charge any fee for such copies and
further provided that each copy contains this Copyright Notice, whether distributed in
print or electronically.

[[dataflow-documentation-getting-help]]
== Getting help
Having trouble with Spring Cloud Data Flow? We would like to help!

* Ask a question. We monitor https://stackoverflow.com[stackoverflow.com] for questions
tagged with https://stackoverflow.com/tags/spring-cloud-dataflow[`spring-cloud-dataflow`].
* Report bugs with Spring Cloud Data Flow at https://github.com/spring-cloud/spring-cloud-dataflow/issues.
* Chat with the community and developers on https://gitter.im/spring-cloud/spring-cloud-dataflow[Gitter].

NOTE: All of Spring Cloud Data Flow is open source, including the documentation! If you find problems
with the docs or if you just want to improve them, please {github-code}[get involved].
