[[dataflow-documentation]]
= Spring Cloud Data Flow Overview

[partintro]
--
This section provides a brief overview of the Spring Cloud Data Flow reference documentation. Think of
it as map for the rest of the document. You can read this reference guide in a linear
fashion, or you can skip sections if something doesn't interest you.
--

[[dataflow-documentation-intro]]
== Introducing Spring Cloud Data Flow
Spring Cloud Data Flow is a cloud native programming and operating model for composable data microservices on modern runtimes.  With Spring Cloud Data Flow, developers can create and orchestrate data pipelines for common use cases such as data ingest, real-time analytics, and data import/export.

Spring Cloud Data Flow is the cloud native redesign of link:https://projects.spring.io/spring-xd/[Spring XD] – a project that aimed to simplify development of Big Data applications.  The streaming and batch modules from Spring XD are refactored into Spring Boot link:https://cloud.spring.io/spring-cloud-stream-modules/[data microservice] applications that are now autonomous deployment units and they can "natively" run in modern runtimes such as Cloud Foundry, Apache YARN, Apache Mesos, and Kubernetes.

Spring Cloud Data Flow offers a collection of patterns and best practices for microservices-based distributed streaming and batch data pipelines. 

=== Features

* Orchestrate applications across a variety of distributed modern runtimes including: Cloud Foundry, Apache YARN, Apache Mesos, and Kubernetes
* Separate runtime dependencies backed by *spring profiles*
* Consume stream and batch data-microservices as maven dependencies
* Develop using: DSL, Shell, REST-APIs, Data Flow Server UI, and Flo
* Take advantage of metrics, health checks and remote management of each data microservice
* Scale stream and batch pipelines without interrupting data flows

