[[dataflow-documentation]]
= Spring Cloud Data Flow Overview

[partintro]
--
This section provides a brief overview of the Spring Cloud Data Flow reference documentation. Think of
it as map for the rest of the document. You can read this reference guide in a linear
fashion, or you can skip sections if something doesn't interest you.
--

[[dataflow-documentation-about]]
== About the documentation
The Spring Cloud Data Flow reference guide is available as {spring-cloud-dataflow-docs}/html[html],
{spring-cloud-dataflow-docs}/pdf/spring-cloud-dataflow-reference.pdf[pdf]
and {spring-cloud-dataflow-docs}/epub/spring-cloud-dataflow-reference.epub[epub] documents. The latest copy
is available at {spring-cloud-dataflow-docs-current}.

Copies of this document may be made for your own use and for
distribution to others, provided that you do not charge any fee for such copies and
further provided that each copy contains this Copyright Notice, whether distributed in
print or electronically.


[[dataflow-documentation-getting-help]]
== Getting help
Having trouble with Spring Boot, We'd like to help!

* Try the <<howto.adoc#howto, How-to's>> -- they provide solutions to the most common
  questions.
* Ask a question - we monitor http://stackoverflow.com[stackoverflow.com] for questions
  tagged with http://stackoverflow.com/tags/spring-cloud[`spring-cloud`].
* Report bugs with Spring Boot at https://github.com/spring-cloud/spring-cloud-dataflow/issues.

NOTE: All of Spring Cloud Data Flow is open source, including the documentation! If you find problems
with the docs; or if you just want to improve them, please {github-code}[get involved].

[[dataflow-documentation-intro]]
== Introducing Spring Cloud Data Flow
We'd like to introduce Spring Cloud Data Flow which is a ...

== Spring Cloud Data Flow Architecture
The architecture for Spring Cloud Data Flow is ...



