[[dataflow-documentation]]
= Spring Cloud Data Flow Overview

[partintro]
--
This section provides a brief overview of the Spring Cloud Data Flow reference documentation. Think of
it as map for the rest of the document. You can read this reference guide in a linear
fashion, or you can skip sections if something doesn't interest you.
--

[[dataflow-documentation-intro]]
== Introducing Spring Cloud Data Flow
A cloud native programming and operating model for composable data microservices on a structured platform. 
With Spring Cloud Data Flow, developers can create, orchestrate and refactor data pipelines through single programming model for common use cases such as data ingest, real-time analytics, and data import/export.

Spring Cloud Data Flow is the cloud native redesign of link:http://projects.spring.io/spring-xd/[Spring XD] – a project that aimed to simplify development of Big Data applications. The integration and batch modules from Spring XD are refactored into Spring Boot link:http://cloud.spring.io/spring-cloud-stream-modules/[data microservices] applications that are now autonomous deployment units – thus enabling them to take full advantage of platform capabilities "natively", and they can independently evolve in isolation.

Spring Cloud Data Flow defines best practices for distributed stream and batch microservice design patterns.

=== Features

* Orchestrate applications across a variety of distributed runtime platforms including: Cloud Foundry, Apache YARN, Apache Mesos, and Kubernetes
* Separate runtime dependencies backed by ‘spring profiles’
* Consume stream and batch data-microservices as maven dependency
* Develop using: DSL, Shell, REST-APIs, Admin-UI, and Flo
* Take advantage of metrics, health checks and remote management of data-microservices
* Scale stream and batch pipelines without interrupting data flows


== Spring Cloud Data Flow Architecture

The architecture for Spring Cloud Data Flow is separated into a number of distinct components.

=== Components

The link:https://github.com/spring-cloud/spring-cloud-dataflow/tree/master/spring-cloud-dataflow-core[Core]
domain model includes the concept of a **stream** that is a composition of spring-cloud-stream
apps in a linear pipeline from a *source* to a *sink*, optionally including *processor* apps
in between. The domain also includes the concept of a **task**, which may be any process that does
not run indefinitely, including link:https://github.com/spring-projects/spring-batch[Spring Batch] jobs.

The link:https://github.com/spring-cloud/spring-cloud-dataflow/tree/master/spring-cloud-dataflow-registry[App Registry]
maintains the set of available apps, and their mappings to a URI.
For example, if relying on Maven coordinates, the URI would be of the format:
`maven://<groupId>:<artifactId>:<version>`

The link:https://github.com/spring-cloud/spring-cloud-dataflow/tree/master/spring-cloud-dataflow-server-core[Data Flow Server Core]
provides the REST API and UI to be used in combination with an implementation of the Deployer SPI
when creating a Data Flow Server for a given deployment environment.

The link:https://github.com/spring-cloud/spring-cloud-dataflow/tree/master/spring-cloud-dataflow-shell[Shell]
connects to the Data Flow Server's REST API and supports a DSL that simplifies the process of
defining a stream and managing its lifecycle.

Several Data Flow Server implementations exist, covering a range of runtime environments:

* link:https://github.com/spring-cloud/spring-cloud-dataflow/tree/master/spring-cloud-dataflow-server-local[Local] (intended for development only)

* link:https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry[Cloud Foundry]

* link:https://github.com/spring-cloud/spring-cloud-dataflow-server-yarn[Apache Yarn]

* link:https://github.com/spring-cloud/spring-cloud-dataflow-server-mesos[Apache Mesos]

* link:https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes[Kubernetes]

As mentioned above, the Spring Cloud Data Flow Server implementations all rely upon corresponding
implementations of the link:https://github.com/spring-cloud/spring-cloud-deployer[Spring Cloud Deployer]
SPI, which provides the abstraction layer for deploying the apps of a given stream or task. The
following are links to the deployer SPI projects that correspond to the Data Flow Servers listed above:

* link:https://github.com/spring-cloud/spring-cloud-deployer/tree/master/spring-cloud-deployer-local[Local]

* link:https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry[Cloud Foundry]

* link:https://github.com/spring-cloud/spring-cloud-deployer-yarn[Apache Yarn]

* link:https://github.com/spring-cloud/spring-cloud-deployer-mesos[Apache Mesos]

* link:https://github.com/spring-cloud/spring-cloud-deployer-kubernetes[Kubernetes]
