
[[spring-cloud-stream-overview]]
= Spring Cloud Stream Overview

[partintro]
--
This section goes into more detail about how you can work with Spring Cloud Stream. It covers topics
such as creating and running stream applications.

If you're just starting out with Spring Cloud Data Flow, you should probably read the
_<<getting-started.adoc#getting-started, Getting Started>>_ guide before diving into
this section.
--

== Introducing Spring Cloud Stream

The Spring Cloud Stream project allows a user to develop and run messaging microservices using Spring Integration and run them locally or in the cloud, either as standalone apps or via Spring Cloud Data Flow. Just add `@EnableBinding` and run your app as a Spring Boot app (single application context). You just need to connect to the physical broker for the bindings, which is automatic if the relevant binder implementation is available on the classpath (e.g. Kafka or RabbitMQ).

Here's a sample source application (output channel only):

[source,java]
----
@SpringBootApplication
@ComponentScan(basePackageClasses=TimerSource.class)
public class TimerSourceApplication {

  public static void main(String[] args) {
    SpringApplication.run(TimerSourceApplication.class, args);
  }

}

@Configuration
@EnableBinding(Source.class)
public class TimerSource {

  @Value("${format}")
  private String format;

  @Bean
  @InboundChannelAdapter(value = Source.OUTPUT, poller = @Poller(fixedDelay = "${fixedDelay}", maxMessagesPerPoll = "1"))
  public MessageSource<String> timerMessageSource() {
    return () -> new GenericMessage<>(new SimpleDateFormat(format).format(new Date()));
  }

}
----

`@EnableBinding` is parameterized by an interface (in this case `Source`) which declares input and output channels. `Source`, `Sink` and `Processor` are provided off the shelf, but you can define others. Here's the definition of `Source`:

[source,java]
----
public interface Source {
  @Output("output")
  MessageChannel output();
}
----

The `@Output` annotation is used to identify output channels (messages leaving the app) and `@Input` is used to identify input channels (messages entering the app). It is optionally parameterized by a channel name - if the name is not provided the method name is used instead. An implementation of the interface is created for you and can be used in the application context by autowiring it, e.g. into a test case:

[source,java]
----
@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = TimerSourceApplication.class)
@WebAppConfiguration
@DirtiesContext
public class TimerSourceApplicationTests {

	@Autowired
	private Source source

	@Test
	public void contextLoads() {
		assertNotNull(this.source.output());
	}

}
----

NOTE: In this case there is only one `Source` in the application context so there is no need to qualify it when it is autowired. If there is ambiguity, e.g. if you are composing one app from some others, you can use the `@Bindings` qualifier to inject a specific channel set. The `@Bindings` qualifier takes a parameter which is the class that carries the `@EnableBinding` annotation (in this case the `TimerSource`).

For more information, including how to run `spring-cloud-stream` applications autonomously (without Spring Cloud Data Flow),
visit the link:https://cloud.spring.io/spring-cloud-stream[Spring Cloud Stream project home page].
