server:
  port: 9393
info:
  app:
    name: "@project.artifactId@"
    description: "@project.name@"
    version: "@project.version@"

maven:
  remoteRepositories:
    mavenCentral:
      url: https://repo.maven.apache.org/maven2
    springRepo:
      url: https://repo.spring.io/snapshot

spring:
  application:
    name: spring-cloud-dataflow-server
  cloud:
    config:
      uri: http://localhost:8888

  datasource:
    url: jdbc:h2:tcp://localhost:19092/mem:dataflow
    username: sa
    password:
    driverClassName: org.h2.Driver
