CREATE SEQUENCE HIBERNATE_SEQUENCE START 1 INCREMENT 1;

CREATE TABLE APP_REGISTRATION (
   ID INT8 NOT NULL,
    OBJECT_VERSION INT8,
    DEFAULT_VERSION BOOLEAN,
    METADATA_URI TEXT,
    NAME VARCHAR(255),
    TYPE INT4,
    URI TEXT,
    VERSION VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE AUDIT_RECORDS (
   ID INT8 NOT NULL,
    AUDIT_ACTION INT8 NOT NULL,
    AUDIT_DATA TEXT,
    AUDIT_OPERATION INT8 NOT NULL,
    CORRELATION_ID VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_ON TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS AUDIT_RECORDS_AUDIT_ACTION_IDX ON AUDIT_RECORDS (AUDIT_ACTION) ;
CREATE INDEX IF NOT EXISTS AUDIT_RECORDS_AUDIT_OPERATION_IDX ON AUDIT_RECORDS (AUDIT_OPERATION) ;
CREATE INDEX IF NOT EXISTS AUDIT_RECORDS_CORRELATION_ID_IDX ON AUDIT_RECORDS (CORRELATION_ID) ;
CREATE INDEX IF NOT EXISTS AUDIT_RECORDS_CREATED_ON_IDX ON AUDIT_RECORDS (CREATED_ON) ;
