
#!/bin/bash
## **This is an autogenerated file, do not change it manually**

if test -z "$BASH_VERSION"; then
  echo "Please run this script using bash, not sh or any other shell." >&2
  exit 1
fi

install() {
  set -euo pipefail


  if [ -x "$(command -v wget)" ]; then
    dl_bin="wget -nv -O-"
  else
    dl_bin="curl -s -L"
  fi



  echo "Downloading manifests..."
  mkdir -p manifests-download


  echo "Downloading cert-manager..."
  $dl_bin https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml > ./manifests-download/cert-manager.yaml
  echo "Downloaded yaml for cert-manager v1.11.0"
  
  echo "Downloading secretgen..."
  $dl_bin https://github.com/carvel-dev/secretgen-controller/releases/download/v0.13.1/release.yml > ./manifests-download/secretgen-controller.yaml
  echo "Downloaded yaml for secretgen v0.13.1"
  
  echo "Downloading kapp-controller..."
  $dl_bin https://github.com/carvel-dev/kapp-controller/releases/download/v0.44.6/release.yml > ./manifests-download/kapp-controller.yaml
  echo "Downloaded yaml for kapp-controller v0.44.6"
  
}

install
