
#!/bin/bash
## **This is an autogenerated file, do not change it manually**

if test -z "$BASH_VERSION"; then
  echo "Please run this script using bash, not sh or any other shell." >&2
  exit 1
fi

install() {
  set -euo pipefail

  dst_dir="${K14SIO_INSTALL_BIN_DIR:-/usr/local/bin}"

  shasum -v 1>/dev/null 2>&1 || (echo "Missing shasum binary" && exit 1)

  if [[ `uname` == Darwin ]]; then
    binary_type=darwin-amd64
  else
    binary_type=linux-amd64
  fi

  echo "Installing ${binary_type} binaries..."

  
  echo "Installing ytt..."

  mv carvel-download/ytt-${binary_type} ${dst_dir}/ytt
  chmod +x ${dst_dir}/ytt
  echo "Installed ${dst_dir}/ytt v0.44.3"
  
  echo "Installing imgpkg..."

  mv carvel-download/imgpkg-${binary_type} ${dst_dir}/imgpkg
  chmod +x ${dst_dir}/imgpkg
  echo "Installed ${dst_dir}/imgpkg v0.36.0"
  
  echo "Installing kbld..."

  mv carvel-download/kbld-${binary_type} ${dst_dir}/kbld
  chmod +x ${dst_dir}/kbld
  echo "Installed ${dst_dir}/kbld v0.36.4"
  
  echo "Installing kapp..."

  mv carvel-download/kapp-${binary_type} ${dst_dir}/kapp
  chmod +x ${dst_dir}/kapp
  echo "Installed ${dst_dir}/kapp v0.54.3"
  
  echo "Installing kwt..."

  mv carvel-download/kwt-${binary_type} ${dst_dir}/kwt
  chmod +x ${dst_dir}/kwt
  echo "Installed ${dst_dir}/kwt v0.0.6"
  
  echo "Installing vendir..."

  mv carvel-download/vendir-${binary_type} ${dst_dir}/vendir
  chmod +x ${dst_dir}/vendir
  echo "Installed ${dst_dir}/vendir v0.32.5"
  
  echo "Installing kctrl..."

  mv carvel-download/kctrl-${binary_type} ${dst_dir}/kctrl
  chmod +x ${dst_dir}/kctrl
  echo "Installed ${dst_dir}/kctrl v0.44.6"
  
}

install
