name: Publish Bundle
description: Publish Bundle
inputs:
  path:
    description: path to bundle files
    required: true
  repository:
    description: repository to publish
    required: true
  version:
    description: semver version
    required: true
  
runs:
  using: "composite"
  steps:
  - name: Setup Envs
    shell: bash
    run: |
      echo RTAG=R$(date +%y%m%d%s%N) >> $GITHUB_ENV
  - name: Tanzu Dance
    id: tanzu-dance
    env:
      BUNDLE_PATH: ${{ inputs.path }}
      REPOSITORY: ${{ inputs.repository }}
      VERSION: ${{ inputs.version }}
    shell: bash
    run: |
      imgpkg push --bundle $REPOSITORY:$VERSION-RANDOM.$RTAG --file $BUNDLE_PATH
      docker pull $REPOSITORY:$VERSION-RANDOM.$RTAG
      docker tag $REPOSITORY:$VERSION-RANDOM.$RTAG $REPOSITORY:$VERSION
      docker push $REPOSITORY:$VERSION
