apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: mariadb:10.4
        name: mariadb
        env:
          - name: LANG
            value: en_US.utf8
          - name: LC_ALL
            value: en_US.utf8
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: mariadb
        ports:
          - containerPort: 3306
            name: mariadb
        volumeMounts:
          - name: data
            mountPath: /var/lib/mariadb
        args:
          - "--ignore-db-dir=lost+found"
          - "--character-set-server=utf8mb4"
          - "--collation-server=utf8mb4_unicode_ci"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mariadb
