CREATE INDEX BATCH_JOB_EXECUTION_PARAMS_JOB_EXECUTION_ID_IDX ON BATCH_JOB_EXECUTION_PARAMS (JOB_EXECUTION_ID) ;
CREATE INDEX TASK_EXECUTION_PARAMS_TASK_EXECUTION_ID_IDX ON TASK_EXECUTION_PARAMS (TASK_EXECUTION_ID) ;
CREATE INDEX BATCH_JOB_INSTANCE_JOB_KEY_IDX ON BATCH_JOB_INSTANCE (JOB_KEY,JOB_NAME) ;
CREATE INDEX BATCH_STEP_EXECUTION_JOB_EXECUTION_ID_IDX ON BATCH_STEP_EXECUTION (JOB_EXECUTION_ID) ;
