
    CREATE TABLE APP_REGISTRATION (
       ID BIGINT NOT NULL,
        OBJECT_VERSION BIGINT,
        DEFAULT_VERSION BIT,
        METADATA_URI LONGTEXT,
        NAME VARCHAR(255),
        TYPE INTEGER,
        URI LONGTEXT,
        VERSION VARCHAR(255),
        PRIMARY KEY (ID)
    );

    CREATE TABLE AUDIT_RECORDS (
       ID BIGINT NOT NULL,
        AUDIT_ACTION BIGINT NOT NULL,
        AUDIT_DATA LONGTEXT,
        AUDIT_OPERATION BIGINT NOT NULL,
        CORRELATION_ID VARCHAR(255),
        CREATED_BY VARCHAR(255),
        CREATED_ON DATETIME,
        PRIMARY KEY (ID)
    );

    CREATE INDEX AUDIT_RECORDS_AUDIT_ACTION_IDX ON AUDIT_RECORDS (AUDIT_ACTION) ;
    CREATE INDEX AUDIT_RECORDS_AUDIT_OPERATION_IDX ON AUDIT_RECORDS (AUDIT_OPERATION) ;
    CREATE INDEX AUDIT_RECORDS_CORRELATION_ID_IDX ON AUDIT_RECORDS (CORRELATION_ID) ;
    CREATE INDEX AUDIT_RECORDS_CREATED_ON_IDX ON AUDIT_RECORDS (CREATED_ON) ;

    CREATE TABLE HIBERNATE_SEQUENCE (
        NEXT_VAL BIGINT
    );

    INSERT INTO HIBERNATE_SEQUENCE(NEXT_VAL) SELECT * FROM (SELECT 1) AS TMP WHERE NOT EXISTS ( SELECT NEXT_VAL FROM HIBERNATE_SEQUENCE) LIMIT 1;
