{
 "title": "Servers",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "application", "query": "label_values(application)" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\"}*1000"
    }
   ]
  },
  {
   "title": "Heap usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"$application\"}"
    }
   ]
  },
  {
   "title": "System CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$application\"}"
    }
   ]
  },
  { "title": "HTTP API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Slowest HTTP requests",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topK(25, sum(http_server_requests_seconds_count{application=\"$application\"}) by (uri))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "HTTP Percentiles (last 5 min)",
   "type": "graph",
   "description": "The request duration within which you have served 95% of requests.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(http_server_requests_seconds_bucket{application=\"$application\"}[5m])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95,sum(rate(http_server_requests_seconds_bucket{application=\"$application\"}[5m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.90,sum(rate(http_server_requests_seconds_bucket{application=\"$application\"}[5m])) by (le))",
     "legendFormat": "90th"
    }
   ]
  },
  {
   "title": "HTTP Durration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\", status!~\"5..\"}[60s]))/sum(rate(http_server_requests_seconds_count{application=\"$application\", status!~\"5..\"}[60s]))",
     "legendFormat": "avg latency per req"
    },
    {
     "expr": "max(http_server_requests_seconds_max{application=\"$application\", status!~\"5..\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "HTTP Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(rate(http_server_requests_seconds_count{application=\"$application\"}[60s])) by (method)"
    }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", status=~\"5..\"}[60s])) by (method)"
    }
   ]
  },
  { "title": "Logging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Logs Rate",
   "type": "bargauge",
   "description": "Rate of of log messages emit by the applicaiton",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topK(10, sum(irate(logback_events_total{application=\"$application\"}[60s])) by (level))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "increase(logback_events_total{application=\"$application\"}[1m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  { "title": "Datasource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Slowest Query",
   "type": "stat",
   "description": "he time of the slowest query",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hibernate_query_executions_max_seconds{application=\"$application\"}",
     "legendFormat": "ms"
    }
   ]
  },
  {
   "title": "Slowest natural Id",
   "type": "stat",
   "description": "The maximum query time for naturalId queries executed against the database.",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hibernate_query_natural_id_executions_max_seconds{application=\"spring-cloud-dataflow-server\"}",
     "legendFormat": "ms"
    }
   ]
  },
  {
   "title": "Collections",
   "type": "graph",
   "description": "* **deletes** - rate of collection deletes.\n* **fetches**  - rate of collection fetches.\n* **loads**  - rate of collection loads.\n* **recreates** - rate of collection recreates.\n* **updates** - rate of collection updates.\n",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(hibernate_collections_deletes_total{application=\"spring-cloud-dataflow-server\"}[60s])",
     "legendFormat": "deletes"
    },
    {
     "expr": "rate(hibernate_collections_fetches_total{application=\"spring-cloud-dataflow-server\"}[60s])",
     "legendFormat": "fetches"
    },
    {
     "expr": "rate(hibernate_collections_loads_total{application=\"spring-cloud-dataflow-server\"}[60s])",
     "legendFormat": "loads"
    },
    {
     "expr": "rate(hibernate_collections_recreates_total{application=\"spring-cloud-dataflow-server\"}[60s])",
     "legendFormat": "recreates"
    },
    {
     "expr": "rate(hibernate_collections_updates_total{application=\"spring-cloud-dataflow-server\"}[60s])",
     "legendFormat": "updates"
    }
   ]
  },
  {
   "title": "Session Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(hibernate_sessions_open_total{application=\"$application\"}[60s])",
     "legendFormat": "open"
    },
    {
     "expr": "rate(hibernate_sessions_closed_total{application=\"$application\"}[60s])",
     "legendFormat": "closed"
    }
   ]
  },
  {
   "title": "Transactions Rate",
   "type": "graph",
   "description": "JPA Transactions Rate",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(hibernate_transactions_total{application=\"$application\"}[60s])",
     "legendFormat": "{{result}}"
    },
    {
     "expr": "rate(hibernate_optimistic_failures_total{application=\"$application\"}[60s])",
     "legendFormat": "optimistic failures"
    }
   ]
  },
  {
   "title": "Update Timestamp Cache",
   "type": "graph",
   "description": "* **hit** - rate of timestamps successfully retrieved from cache.\n* **miss** -  rate of of tables for which no update timestamps was not found in cache.\n* **puts** - rate of of timestamps put in cache.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(hibernate_cache_update_timestamps_requests_total{application=\"$application\"}[60s])",
     "legendFormat": "{{result}}"
    },
    {
     "expr": "rate(hibernate_cache_update_timestamps_puts_total{application=\"$application\"}[60s])",
     "legendFormat": "puts"
    }
   ]
  },
  {
   "title": "Query Rate",
   "type": "graph",
   "description": "* **total** - rate of the executed queries\n* **max** - the time of the slowest query",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(hibernate_query_executions_total{application=\"$application\"}[60s])",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Query Caching",
   "type": "graph",
   "description": "* **hit** - rate of cached queries successfully retrieved from cache\n* **miss** - rate of cached queries not found in cache\n* **put** - rate of cacheable queries put in cache",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(hibernate_cache_query_requests_total{application=\"$application\"}[60s])",
     "legendFormat": "{{result}}"
    },
    {
     "expr": "rate(hibernate_cache_query_puts_total{application=\"$application\"}[60s])",
     "legendFormat": "puts"
    }
   ]
  },
  {
   "title": "Second Level Caching",
   "type": "graph",
   "description": "* **hit** - rate of cacheable entities/collections successfully retrieved from the cache\n* **miss** -  rate of cacheable entities/collections not found in the cache and loaded from the database\n* **put** - rate of cacheable entities/collections put in the cache",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(hibernate_second_level_cache_requests_total{application=\"$application\"}[60s])",
     "legendFormat": "{{result}}"
    },
    {
     "expr": "rate(hibernate_second_level_cache_puts_total{application=\"$application\"}[60s])",
     "legendFormat": "puts"
    }
   ]
  },
  {
   "title": "Natural Id Cache",
   "type": "graph",
   "description": "**hit** - rate of cached naturalId lookups successfully retrieved from cache.\n\n**miss** -  rate of cached naturalId lookups not found in cache.\n\n**puts** - rate of cacheable naturalId lookups put in cache.\n\n**query_natural** - rate of of naturalId queries executed against the database.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(hibernate_cache_natural_id_requests_total{application=\"$application\"}[60s])",
     "legendFormat": "{{result}}"
    },
    {
     "expr": "rate(hibernate_cache_natural_id_puts_total{application=\"$application\"}[60s])",
     "legendFormat": "puts"
    },
    {
     "expr": "rate(hibernate_query_natural_id_executions_total{application=\"$application\"}[60s])",
     "legendFormat": "query_natural"
    }
   ]
  },
  {
   "title": "Flushes / Obtained Connections",
   "type": "graph",
   "description": "* **flushes** - rate of flushes executed by sessions (either implicit or explicit).\n* **obtained** -  rate of connections number asked by the sessions. The actual number of connections used may be much smaller depending  whether you use a connection pool or not.",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(hibernate_flushes_total{application=\"$application\"}[60s])",
     "legendFormat": "flushes per session"
    },
    {
     "expr": "rate(hibernate_connections_obtained_total{application=\"$application\"}[60s])",
     "legendFormat": "obtained connections per sessions"
    }
   ]
  },
  {
   "title": "Statements",
   "type": "graph",
   "description": "* **prepared** - rate of prepared statements that were acquired.\n* **closed** - rate of prepared statements that were released.",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(hibernate_statements_total{application=\"spring-cloud-dataflow-server\"}[60s])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Entity information",
   "type": "graph",
   "description": "* **deletes** - rate of entity deletes.\n* **inserts** - rate of entity inserts.\n* **fetches** - rate of entity inserts.\n* **loads** - rate of entity loads.\n* **updates** - rate of entity updates.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(hibernate_entities_deletes_total{application=\"$application\"}[60s])",
     "legendFormat": "deletes"
    },
    {
     "expr": "rate(hibernate_entities_inserts_total{application=\"$application\"}[60s])",
     "legendFormat": "inserts"
    },
    {
     "expr": "rate(hibernate_entities_fetches_total{application=\"$application\"}[60s])",
     "legendFormat": "fetches"
    },
    {
     "expr": "rate(hibernate_entities_loads_total{application=\"$application\"}[60s])",
     "legendFormat": "loads"
    },
    {
     "expr": "rate(hibernate_entities_updates_total{application=\"$application\"}[60s])",
     "legendFormat": "updates"
    }
   ]
  },
  { "title": "JDBC Connection Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Total Connections",
   "type": "stat",
   "description": "HikariCP Total connections.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(hikaricp_connections{application=\"$application\"}) by (pool)",
     "legendFormat": "ms"
    }
   ]
  },
  {
   "title": "Idle Connections",
   "type": "stat",
   "description": "HikariCP Idle Connections",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(hikaricp_connections_idle{application=\"$application\"}) by (pool)"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "description": "HikariCP Active Connections",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(hikaricp_connections_active{application=\"$application\"}) by (pool)"
    }
   ]
  },
  {
   "title": "Pending Connections",
   "type": "stat",
   "description": "HikariCP Pending Connections",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(hikaricp_connections_pending{application=\"$application\"}) by (pool)"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "description": "HikariCP Max Connections",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(hikaricp_connections_max{application=\"$application\"}) by (pool)"
    }
   ]
  },
  {
   "title": "Min Connections",
   "type": "stat",
   "description": "HikariCP Min Connections",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(hikaricp_connections_min{application=\"$application\"}) by (pool)"
    }
   ]
  },
  {
   "title": "HikariCP Connection Times",
   "type": "graph",
   "description": "* **acquire** - average connection acquire time per request.\n* **creation** - average connection creation time per request.\n* **usage** - average connection usage time per request.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hikaricp_connections_acquire_seconds_sum{application=\"$application\"}[60s]) / rate(hikaricp_connections_acquire_seconds_count{application=\"$application\"}[60s])) by (pool)",
     "legendFormat": "Acquire time ({{pool}})"
    },
    {
     "expr": "sum(rate(hikaricp_connections_creation_seconds_sum{application=\"$application\"}[60s]) / rate(hikaricp_connections_creation_seconds_count{application=\"$application\"}[60s])) by (pool)",
     "legendFormat": "Creation time ({{pool}})"
    },
    {
     "expr": "sum(rate(hikaricp_connections_usage_seconds_sum{application=\"$application\"}[60s]) / rate(hikaricp_connections_usage_seconds_count{application=\"$application\"}[60s])) by (pool)",
     "legendFormat": "Usage time ({{pool}})"
    }
   ]
  },
  {
   "title": "HikariCP Timeout Rate",
   "type": "graph",
   "description": "Connection pool, timeout rate",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(hikaricp_connections_timeout_total{application=\"$application\"}[60s])) by (pool)",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "JDBC Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jdbc_connections_active{application=\"$application\"}",
     "legendFormat": "active"
    },
    {
     "expr": "jdbc_connections_idle{application=\"$application\"}",
     "legendFormat": "idle"
    },
    {
     "expr": "jdbc_connections_max{application=\"$application\"}",
     "legendFormat": "max"
    },
    {
     "expr": "jdbc_connections_min{application=\"$application\"}",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "system_cpu_usage{application=\"$application\"}",
       "legendFormat": "system"
      },
      {
       "expr": "process_cpu_usage{application=\"$application\"}",
       "legendFormat": "process"
      },
      {
       "expr": "avg_over_time(process_cpu_usage{application=\"$application\"}[1h])",
       "legendFormat": "process-1h"
      }
     ]
    },
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_load_average_1m{application=\"$application\"}",
       "legendFormat": "system-1m"
      },
      {
       "expr": "system_cpu_count{application=\"$application\"}",
       "legendFormat": "cpus"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_live_threads{application=\"$application\"}",
       "legendFormat": "live"
      },
      {
       "expr": "jvm_threads_daemon_threads{application=\"$application\"}",
       "legendFormat": "daemon"
      },
      {
       "expr": "jvm_threads_peak_threads{application=\"$application\"}",
       "legendFormat": "peak"
      },
      {
       "expr": "process_threads{application=\"$application\"}",
       "legendFormat": "process"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{application=\"$application\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "JVM Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{application=\"$application\", area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Non-Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", area=\"nonheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", area=\"nonheap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{application=\"$application\", area=\"nonheap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{application=\"$application\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{application=\"$application\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Process Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_memory_rss_bytes{application=\"$application\"}",
       "legendFormat": "rss"
      },
      {
       "expr": "process_memory_swap_bytes{application=\"$application\"}",
       "legendFormat": "swap"
      },
      {
       "expr": "process_memory_rss_bytes{application=\"$application\"} + process_memory_swap_bytes{application=\"$application\"}",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "GC Collections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{application=\"$application\"}[1m])",
       "legendFormat": "{{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "GC Pause Durations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{application=\"$application\"}[1m])/rate(jvm_gc_pause_seconds_count{application=\"$application\"}[1m])",
       "legendFormat": "avg {{action}} ({{cause}})"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{application=\"$application\"}",
       "legendFormat": "max {{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "GC Allocated/Promoted",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{application=\"$application\"}[1m])",
       "legendFormat": "allocated"
      },
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total{application=\"$application\"}[1m])",
       "legendFormat": "promoted"
      }
     ]
    },
    {
     "title": "Classes loaded",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{application=\"$application\"}",
       "legendFormat": "loaded"
      }
     ]
    },
    {
     "title": "Class delta",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(jvm_classes_loaded_classes{application=\"$application\"}[1m])",
       "legendFormat": "delta-1m"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", id=\"direct\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{application=\"$application\", id=\"direct\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count_buffers{application=\"$application\", id=\"direct\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", id=\"mapped\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{application=\"$application\", id=\"mapped\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Mapped Buffers Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count_buffers{application=\"$application\", id=\"mapped\"}",
       "legendFormat": "count"
      }
     ]
    }
   ]
  }
 ]
}