[appendix]
[[contributing]]
== Contributing
Spring Cloud is released under the non-restrictive Apache 2.0 license and follows a standard Github development process, using Github tracker for issues and merging pull requests into master.
If you want to contribute even something trivial, please do not hesitate, but please do follow the guidelines spelled out in this section.

=== Sign the Contributor License Agreement
Before we accept a non-trivial patch or pull request, we need you to sign the https://cla.pivotal.io[contributor's agreement].
Signing the contributor's agreement does not grant anyone commit rights to the main repository, but it does mean that we can accept your contributions.
You will get an author credit if we do.
Active contributors might be asked to join the core team and be given the ability to merge pull requests.

=== Code Conventions and Housekeeping
None of these conventions is essential for a pull request, but they all help.
They can also be added after the original pull request but before a merge.

* Use the Spring Framework code format conventions.
Follow https://github.com/spring-cloud/spring-cloud-skipper#code-formatting-guidelines[these instructions] for setting up the eclipse formatter in eclipse or IntelliJ.
Note that checkstyle is enabled in the build.
* Make sure all new `.java` files have a simple Javadoc class comment with at least an `@author` tag identifying you and preferably at least a paragraph on what the class is for.
* Add the ASF license header comment to all new `.java` files.
To do so, copy from existing files in the project.
* Add yourself as an `@author` to the `.java` files that you modify substantially (more than cosmetic changes).
* Add some Javadocs and, if you change the namespace, some XSD doc elements.
* A few unit tests would help a lot as well -- someone has to do it, and your fellow developers appreciate it.
* If no-one else is using your branch, please rebase it against the current master (or other target branch in the main project).
* When writing a commit message, please follow https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html[these conventions].
If you are fixing an existing issue, please add `Fixes gh-XXXX` at the end of the commit message (where XXXX is the issue number).
