[[skipper-commands-reference]]
= Skipper Commands

Skipper commands fit into the following categories:

* <<skipper-commands-package>>
* <<skipper-commands-release>>
* <<skipper-commands-manifest>>
* <<skipper-commands-platform>>
* <<skipper-commands-repository>>
* <<skipper-commands-config>>

[[skipper-commands-package]]
== Package Commands

Skipper's package commands include the following:

* <<skipper-commands-package-search>>
* <<skipper-commands-package-upload>>
* <<skipper-commands-package-install>>
* <<skipper-commands-package-delete>>

[[skipper-commands-package-search]]
=== Search
The  `search` command shows all the packages available to be installed by the Skipper server, as shown (with output) in the following example:

[source,bash,options="nowrap"]
----
skipper:>package search
╔═════════════════╤═══════╤════════════════════════════════════════════════════════════════════════════════╗
║      Name       │Version│                                  Description                                   ║
╠═════════════════╪═══════╪════════════════════════════════════════════════════════════════════════════════╣
║helloworld       │1.0.0  │The app has two endpoints, /about and /greeting in English.  Maven resource.    ║
║helloworld       │1.0.1  │The app has two endpoints, /about and /greeting in Portuguese.  Maven resource. ║
║helloworld-docker│1.0.1  │The app has two endpoints, /about and /greeting in Portuguese.  Docker resource.║
║helloworld-docker│1.0.0  │The app has two endpoints, /about and /greeting in English.  Docker resource.   ║
╚═════════════════╧═══════╧════════════════════════════════════════════════════════════════════════════════╝
----

The `search` command can use `--name` option to search for the package name containing the given option value, as shown (with output) in the following example:

[source,bash,options="nowrap"]
----
skipper:>package search --name helloworld-
╔═════════════════╤═══════╤════════════════════════════════════════════════════════════════════════════════╗
║      Name       │Version│                                  Description                                   ║
╠═════════════════╪═══════╪════════════════════════════════════════════════════════════════════════════════╣
║helloworld-docker│1.0.0  │The app has two endpoints, /about and /greeting in English.  Docker resource.   ║
║helloworld-docker│1.0.1  │The app has two endpoints, /about and /greeting in Portuguese.  Docker resource.║
╚═════════════════╧═══════╧════════════════════════════════════════════════════════════════════════════════╝
----

To search for more details of the packages, the `--details` option can be used, as shown (with output) in the following example:

[source,bash,options="nowrap"]
----
skipper:>package search --name helloworld- --details
╔════════════════╤═════════════════════════════════════════════════════════════════════════════╗
║      Name      │                                    Value                                    ║
╠════════════════╪═════════════════════════════════════════════════════════════════════════════╣
║apiVersion      │v1                                                                           ║
║origin          │A sample repository for using Skipper                                        ║
║repositoryId    │1                                                                            ║
║kind            │skipper                                                                      ║
║name            │helloworld-docker                                                            ║
║version         │1.0.0                                                                        ║
║packageSourceUrl│https://github.com/markpollack/skipper-sample-repository                     ║
║packageHomeUrl  │https://github.com/markpollack/skipper-sample-repository                     ║
║tags            │web, demo, docker, helloworld                                                ║
║maintainer      │https://github.com/markpollack                                               ║
║description     │The app has two endpoints, /about and /greeting in English.  Docker resource.║
║sha256          │                                                                             ║
║iconUrl         │                                                                             ║
╚════════════════╧═════════════════════════════════════════════════════════════════════════════╝

╔════════════════╤════════════════════════════════════════════════════════════════════════════════╗
║      Name      │                                     Value                                      ║
╠════════════════╪════════════════════════════════════════════════════════════════════════════════╣
║apiVersion      │v1                                                                              ║
║origin          │A sample repository for using Skipper                                           ║
║repositoryId    │1                                                                               ║
║kind            │skipper                                                                         ║
║name            │helloworld-docker                                                               ║
║version         │1.0.1                                                                           ║
║packageSourceUrl│https://github.com/markpollack/skipper-sample-repository                        ║
║packageHomeUrl  │https://github.com/markpollack/skipper-sample-repository                        ║
║tags            │web, demo, docker, helloworld                                                   ║
║maintainer      │https://github.com/markpollack                                                  ║
║description     │The app has two endpoints, /about and /greeting in Portuguese.  Docker resource.║
║sha256          │                                                                                ║
║iconUrl         │                                                                                ║
╚════════════════╧════════════════════════════════════════════════════════════════════════════════╝

----

[[skipper-commands-package-upload]]
=== Upload
This command uploads a package .zip file, as shown (with output) in the following example:

[source,bash,options="nowrap"]
----
skipper:>package upload --path /path-to-package/mypackage-1.0.0.zip
Package uploaded successfully:[mypackage:1.0.0]
----

If no `--repo-name` is set, the `upload` command uses `local` as the repository to upload.

[[skipper-commands-package-install]]
=== Install

This command installs a package, as shown (with output) in the following example:

[source,bash,options="nowrap"]
----
skipper:>package install --release-name helloworldlocal --package-name helloworld --package-version 1.0.0 --properties spec.applicationProperties.server.port=8099
Released helloworldlocal. Now at version v1.
----

If no `package-version` is specified, then the latest package version by the given `package-name` is considered.

If no `platform-name` is specified, the platform name, `default`, is used.

The properties can either be provided through comma separated YAML string by using the `--properties` option or through a YAML
file by using the `--file` option.

[[skipper-commands-package-delete]]
=== Delete

This command deletes a package.
You can only delete a package that is in a local (database backed) repository, as shown (with output) in the following example:
[source,bash,options="nowrap"]
----
skipper:>package delete --package-name helloworld
Can not delete package [helloworld], associated repository [experimental] is remote.
----


[[skipper-commands-release]]
== Release Commands

Skipper's release commands include the following:

* <<skipper-commands-release-list>>
* <<skipper-commands-release-status>>
* <<skipper-commands-release-upgrade>>
* <<skipper-commands-release-rollback>>
* <<skipper-commands-release-history>>
* <<skipper-commands-release-delete>>

[[skipper-commands-release-list]]
=== List

This command lists the latest deployed or failed release, as shown (with output) in the following example:

[source,bash,options="nowrap"]
----
skipper:>release list
╔═══════════════╤═══════╤═════════════════════════╤════════╤═══════════╤══════════════╤════════════╤══════════════════════════════════════════════════════════════════════════════╗
║     Name      │Version│      Last updated       │ Status │  Package  │   Package    │  Platform  │                               Platform Status                                ║
║               │       │                         │        │   Name    │   Version    │    Name    │                                                                              ║
╠═══════════════╪═══════╪═════════════════════════╪════════╪═══════════╪══════════════╪════════════╪══════════════════════════════════════════════════════════════════════════════╣
║helloworldlocal│3      │Mon Oct 30 17:57:41 IST  │DEPLOYED│helloworld │1.0.0         │default     │[helloworldlocal.helloworld-v3], State =                                      ║
║               │       │2017                     │        │           │              │            │[helloworldlocal.helloworld-v3-0=deployed]                                    ║
╚═══════════════╧═══════╧═════════════════════════╧════════╧═══════════╧══════════════╧════════════╧══════════════════════════════════════════════════════════════════════════════╝
----

[[skipper-commands-release-status]]
=== Status

This command shows the `status` of a specific release and version, as shown (with output) in the following example:

[source,bash,options="nowrap"]
----
skipper:>release status --release-name helloworldlocal
╔═══════════════╤═══════════════════════════════════════════════════════════════════════════════════╗
║Last Deployed  │Mon Oct 30 17:53:50 IST 2017                                                       ║
║Status         │DEPLOYED                                                                           ║
║Platform Status│All applications have been successfully deployed.                                  ║
║               │[helloworldlocal.helloworld-v2], State = [helloworldlocal.helloworld-v2-0=deployed]║
╚═══════════════╧═══════════════════════════════════════════════════════════════════════════════════╝
----

If no `--release-version` specified, the latest release version is used.
The following example shows the command with the `--release-version` option:

[source,bash,options="nowrap"]
----
skipper:>release status --release-name helloworldlocal --release-version 1
╔═══════════════╤════════════════════════════════════════════════════════════════════════╗
║Last Deployed  │Mon Oct 30 17:52:57 IST 2017                                            ║
║Status         │DELETED                                                                 ║
║Platform Status│The applications are known to the system, but is not currently deployed.║
║               │[helloworldlocal.helloworld-v1], State = [unknown]                      ║
╚═══════════════╧════════════════════════════════════════════════════════════════════════╝
----

[[skipper-commands-release-upgrade]]
=== Upgrade

This command upgrades a package, as shown (with output) in the following example:

[source,bash,options="nowrap"]
----
skipper:>release upgrade --release-name helloworldlocal --package-name helloworld --package-version 1.0.0 --properties spec.applicationProperties.server.port=9090
helloworldpcf has been upgraded.  Now at version v2.
----

If no `package-version` is specified, the latest package version by the given `--package-name` option is considered.
The properties can either be provided through comma separated YAML string by using the `--properties` option or through a YAML
file by using the `--file` option.

NOTE: An upgrade can be done by overriding the package version or by keeping the existing package version but overriding the properties.
When overriding the package version, it needs to accompany with the corresponding properties as the existing properties are not carried over.
In a future release, we plan to introduce a `--reuse-properties` command that will carry the current release properties over to the next release to be made.


When performing an update on a package that contains nested packages, use the name of the package as a prefix in the property string or as the first level in the YAML document.
For example, the `ticktock` package that contains a `time` and a `log` application, a command to upgrade the `log` application would be as follows:

[source,bash,options="nowrap"]
----
skipper:>release upgrade --release-name ticktockskipper --package-name ticktock --file /home/mpollack/log-level-change.yml
----

where `log-level-change.yml` contains the following:

[source,bash,options="nowrap"]
----
log:
  version: 1.1.1.RELEASE
  spec:
    applicationProperties:
      server.port: 9999
      endpoints.sensitive: false
      log.level: ERROR
----

Since it is a common use-case to change only the version of the application, the packages can list the version as a top-level property in the `values.yml` file.
For example, in the test package `ticktock` (located https://github.com/spring-cloud/spring-cloud-skipper/blob/master/spring-cloud-skipper-server-core/src/test/resources/repositories/sources/test/ticktock/ticktock-1.0.0/packages/log/values.yml[here]), `values.yml` contains the following:

[source,bash,options="nowrap"]
----
version: 1.1.0.RELEASE
spec:
  applicationProperties:
    log.level: DEBUG
  deploymentProperties:
    memory: 1024m
----

You can then use the `--properties` option in the `upgrade` command, as shown in the following example:

[source,bash,options="nowrap"]
----
skipper:>release upgrade --release-name ticktockskipper --package-name ticktock --properties log.version=1.1.1.RELEASE
----

[[skipper-commands-release-rollback]]
=== Rollback

This command rolls back the release to a specific version, as shown (with output) in the following example:

[source,bash,options="nowrap"]
----
skipper:>release rollback --release-name helloworldlocal --release-version 1
helloworldlocal has been rolled back.  Now at version v3.
----

If no `--release-version` is specified, then the rollback version is the previous stable release (either in `DELETED` or
`DEPLOYED` status).

[[skipper-commands-release-history]]
=== History

This command shows the history of a specific release, as shown (with output) in the following example:

[source,bash,options="nowrap"]
----
skipper:>release history --release-name helloworldlocal
╔═══════╤════════════════════════════╤════════╤════════════╤═══════════════╤════════════════╗
║Version│        Last updated        │ Status │Package Name│Package Version│  Description   ║
╠═══════╪════════════════════════════╪════════╪════════════╪═══════════════╪════════════════╣
║3      │Mon Oct 30 17:57:41 IST 2017│DEPLOYED│helloworld  │1.0.0          │Upgrade complete║
║2      │Mon Oct 30 17:53:50 IST 2017│DELETED │helloworld  │1.0.0          │Delete complete ║
║1      │Mon Oct 30 17:52:57 IST 2017│DELETED │helloworld  │1.0.0          │Delete complete ║
╚═══════╧════════════════════════════╧════════╧════════════╧═══════════════╧════════════════╝
----

[[skipper-commands-release-delete]]
=== Delete

This command deletes a specific release's latest deployed revision, undeploying the application or applications, as shown (with output) in the following example:

[source,bash,options="nowrap"]
----
skipper:>release delete --release-name helloworldlocal
helloworldlocal has been deleted.
----


[[skipper-commands-manifest]]
== Manifest Commands

Skipper's manifest has only one command: `get`.

[[skipper-commands-manifest-get]]
=== Get

The `manifest get` command shows the manifest used for a specific release, as shown (with output) in the following example:

[source,bash,options="nowrap"]
----
skipper:>manifest get --release-name helloworldk8s

---
# Source: template.yml
apiVersion: skipper.spring.io/v1
kind: SpringCloudDeployerApplication
metadata:
  name: helloworld-docker
spec:
  resource: docker:springcloud/spring-cloud-skipper-samples-helloworld:1.0.0.RELEASE
  applicationProperties:
  deploymentProperties:
    spring.cloud.deployer.kubernetes.createNodePort: 32123
----


[[skipper-commands-platform]]
== Platform commands

Skipper's platform has only one command: `list`.

[[skipper-commands-platform-list]]
=== List

The `platform list` command shows the list all the available deployment platform accounts, as shown (with output) in the following example:

```
skipper:>platform list
╔════════╤════════════╤══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║  Name  │    Type    │                                                                         Description                                                                          ║
╠════════╪════════════╪══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╣
║default │local       │ShutdownTimeout = [30], EnvVarsToInherit = [TMP,LANG,LANGUAGE,LC_.*,PATH], JavaCmd =                                                                          ║
║        │            │[/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/bin/java], WorkingDirectoriesRoot = [/var/folders/t3/qf1wkpwj4lgd9gjccwk0wr7h0000gp/T], ║
║        │            │DeleteFilesOnExit = [true]                                                                                                                                    ║
║cf-dev  │cloudfoundry│org = [scdf-ci], space = [ilaya-space], url = [https://api.run.pivotal.io]                                                                                    ║
║minikube│kubernetes  │master url = [https://192.168.99.101:8443/], namespace = [default], api version = [v1]                                                                        ║
╚════════╧════════════╧══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
```

[[skipper-commands-repository]]
== Repository Commands

Skipper's repository has only one command: `list`.

=== List

You can list add or delete a repository using the commands `repo add`, `repo delete` and `repo list`, as shown (with output) in the following example:

```
skipper:>repo list
╔════════════╤═══════════════════════════════════════════════════════════╤═════╤═════╗
║    Name    │                            URL                            │Local│Order║
╠════════════╪═══════════════════════════════════════════════════════════╪═════╪═════╣
║experimental│http://skipper-repository.cfapps.io/repository/experimental│false│0    ║
║local       │http://10.55.13.45:7577                                    │true │1    ║
╚════════════╧═══════════════════════════════════════════════════════════╧═════╧═════╝
```
If a repository is local, it is backed by Skipper's database and you can upload packages to the repository.
If it is not local, it is a remote repository and you can only read packages.
The packages in a remote repository are updated outside of Skipper's control.
The 1.0 release only polls the remote repository for contents upon server startup.
Follow issue https://github.com/spring-cloud/spring-cloud-skipper/issues/262[GH-262] for more on adding support for dynamic updating of remote repository metadata.


[[skipper-commands-config]]
== Skipper Server Commands

Skipper's package commands include the following:

* <<skipper-commands-config-config>>
* <<skipper-commands-config-info>>

[[skipper-commands-config-config]]
=== Config

This command configures the shell to reference the HTTP API endpoint of the Skipper Server, as shown in the following example:

[source,bash]
----
skipper:>skipper config --uri https://localhost:8443/api
----

When using OAuth, you can use the username and password options.


From within the Skipper Shell you can also provide credentials, as shown in the following example:

[source,bash]
----
skipper:> skipper config --uri https://localhost:7577/api --username my_username --password my_password
----

See the "`<<configuration-security>>`" section for more information.

[[skipper-commands-config-info]]
=== Info

This command shows which server version is being used, as shown (with output) in the following example:
[source,bash,subs=attributes]
----
skipper:>info
Spring Cloud Skipper Server v1.0.0.{project-version}
----
