[[skipper-installation]]
= Installation

[[skipper-installation-local]]
== Installing on a local machine

=== Local Platform configuration

Here is an example YAML file to configure two local deployer accounts named `localDev` and `localDevDebug`
```
spring:
  cloud:
    skipper:
      server:
        platform:
          local:
            accounts:
              localDev:
                shutdownTimeout: 60
                javaOpts: "-Dtest=foo"
              localDevDebug:
                javaOpts: "-Xdebug"
```

The key-value pairs that follow the name of the account are `javaCmd`, `workingDirectoriesRoot`, `deleteFilesOnExit`, `envVarsToInherit`, `shutdownTimeout`, `javaOpts`, and `useSpringApplicationJson`.  More information can be found in the JavaDocs for https://github.com/spring-cloud/spring-cloud-deployer-local/blob/master/spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalDeployerProperties.java[LocalDeployerProperties].

[[skipper-installation-cloudfoundry]]
== Installing on Cloud Foundry

=== Cloud Foundry configuration

Here is an example YAML file to configure two Cloud Foundry accounts named `cf-dev` and `cf-qa`

```
spring:
  cloud:
    skipper:
      server:
        platform:
          cloudfoundry:
            accounts:
              cf-dev:
                connection:
                  url: https://api.run.pivotal.io
                  org: myOrg
                  space: mySpace
                  domain: cfapps.io
                  username: cf-dev@example.com
                  password: drowssap
                  skipSslValidation: false
                deployment:
                  memory: 2048m
                  disk: 2048m
                  services: rabbit
              cf-qa:
                connection:
                  url: https://api.run.pivotal.io
                  org: myOrgQA
                  space: mySpaceQA
                  domain: cfapps.io
                  username: cf-qa@example.com
                  password: drowssap
                  skipSslValidation: true
                deployment:
                  memory: 1024m
                  disk: 1024m
                  services: rabbitQA

```

For information on the deployment properties that can be configured can be found in https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/blob/master/src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeploymentProperties.java[CloudFoundryDeploymentProperties].

[[skipper-installation-kubernetes]]
== Installing on Kubernetes

There is a docker image `springcloud/spring-cloud-skipper-server` is available for Skipper server in dockerhub.
You can use this to run the Skipper server in Kubernetes.


[skipper-kubernetes-configuration]
=== Kuberenetes configuration


Here is an example YAML file to configure two accounts named `k8s-dev` and `k8sqa` on a Kubernetes cluster that correspond to different namespaces.  We are investigating how to support connecting to different Kubernetes clusters.

```
spring:
  cloud:
    skipper:
      server:
        platform:
          kubernetes:
            accounts:
              k8s-dev:
                namespace: devNamespace
                cpu: 4
              k8s-qa:
                namespace: qaNamespace
                memory: 1024m
```

More information on the deployment properties that can be configured can be found in https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/master/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesDeployerProperties.java[KubernetesDeployerProperties]

== Database configuration

Spring Cloud Skipper uses a relational database to store metadata. We use https://flywaydb.org/[flyway] to bootstrap and then migrate the database as the product evolves.
We currently provide schemas for the following databases: *H2*, *HSQLDB*, *MySQL*, *PostgreSQL*, *Microsoft SQL Server*, *Oracle 12*, *IBM DB2*.
The JDBC drivers for *MySQL* (via MariaDB driver), *HSQLDB*, *PostgreSQL*, *SQL Server*,  along with embedded *H2* are available out of the box.
If you are using any other database, then the corresponding JDBC driver jar needs to be on the classpath of the server.
If not specified the server will start with the embedded in memory *H2* database.

The database properties can be passed as environment variables or command-line arguments to the Data Flow Server.


* Environment variables:
```
export spring_datasource_url=jdbc:postgresql://localhost:5432/mydb
export spring_datasource_username=myuser
export spring_datasource_password=mypass
export spring_datasource_driver-class-name="org.postgresql.Driver"
```
* Command Line arguments

* *MySQL*
[source,bash]
----
java -jar {skipper_jar} \
    --spring.datasource.url=jdbc:mysql:<db-info> \
    --spring.datasource.username=<user> \
    --spring.datasource.password=<password> \
    --spring.datasource.driver-class-name=org.mariadb.jdbc.Driver &
----

* *PostgreSQL*
[source,bash]
----
java -jar {skipper_jar} \
    --spring.datasource.url=jdbc:postgresql:<db-info> \
    --spring.datasource.username=<user> \
    --spring.datasource.password=<password> \
    --spring.datasource.driver-class-name=org.postgresql.Driver &
----

* *HSQLDB*
[source,bash]
----
java -jar {skipper_jar} \
    --spring.datasource.url=jdbc:hsqldb:mem:<db-info> \
    --spring.datasource.username=sa \
    --spring.datasource.password= \
    --spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver &
----

* *Microsoft SQL Server*
[source,bash]
----
java -jar {skipper_jar} \
    --spring.datasource.url=jdbc:sqlserver://<db-info>;database=<database-name> \
    --spring.datasource.username=<user> \
    --spring.datasource.password=<password> \
    --flyway.schemas=<database-name>
    --spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver &
----

* *Oracle*
[source,bash]
----
java -jar {skipper_jar} \
    --spring.datasource.url=jdbc:oracle:thin:<user>/<password>@<database-address>/<service-id> \
    --spring.datasource.username=<user> \
    --spring.datasource.password=<password> \
    --flyway.schemas=<tablespace-name>
    --spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver &
----

* *IBM DB2*
[source,bash]
----
java -jar {skipper_jar} \
    --spring.datasource.url=jdbc:db2:thin://<db-info>/<db-name> \
    --spring.datasource.username=<user> \
    --spring.datasource.password=<password> \
    --flyway.schemas=<db-name>
    --spring.datasource.driver-class-name=com.ibm.db2.jcc.DB2Driver &
----

NOTE: Please make sure that you configure the correct `flyway.schemas` for *Oracle*, *DB2* and *SQL Server*, otherwise flyway will try to create it's `schema_version` table on the default schema for a connection, which could be different than that your credentials are associated with.
Please refer to the https://flywaydb.org/documentation/[Flyway documentation] for more options.
