[[skipper-installation]]
= Installation

[[skipper-installation-local]]
== Installing on a Local Platform

=== Local Platform configuration

The following example YAML file configures two local deployer accounts, named `localDev` and `localDevDebug`:
```
spring:
  cloud:
    skipper:
      server:
        platform:
          local:
            accounts:
              localDev:
                shutdownTimeout: 60
                javaOpts: "-Dtest=foo"
              localDevDebug:
                javaOpts: "-Xdebug"
```

The key-value pairs that follow the name of the account are `javaCmd`, `workingDirectoriesRoot`, `deleteFilesOnExit`, `envVarsToInherit`, `shutdownTimeout`, `javaOpts`, and `useSpringApplicationJson`.
More information can be found in the JavaDocs for https://github.com/spring-cloud/spring-cloud-deployer-local/blob/master/spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalDeployerProperties.java[LocalDeployerProperties].

[[skipper-installation-cloudfoundry]]
== Installing on Cloud Foundry

This section contains an example YAML file that configures two Cloud Foundry accounts, named `cf-dev` and `cf-qa`.
This is useful on Cloud Foundry if you use the Spring Cloud Config Server to manage Skipper's configuration properties.

=== Cloud Foundry Configuration

You can modify the following sample YML snippet to fit your needs:

[source,yml]
----
spring:
  cloud:
    skipper:
      server:
        enableLocalPlatform: false
        platform:
          cloudfoundry:
            accounts:
              cf-dev:
                connection:
                  url: https://api.run.pivotal.io
                  org: myOrg
                  space: mySpace
                  domain: cfapps.io
                  username: cf-dev@example.com
                  password: drowssap
                  skipSslValidation: false
                deployment:
                  memory: 2048m
                  disk: 2048m
                  services: rabbit
                  deleteRoutes: false
              cf-qa:
                connection:
                  url: https://api.run.pivotal.io
                  org: myOrgQA
                  space: mySpaceQA
                  domain: cfapps.io
                  username: cf-qa@example.com
                  password: drowssap
                  skipSslValidation: true
                deployment:
                  memory: 1024m
                  disk: 1024m
                  services: rabbitQA
                  deleteRoutes: false
----

NOTE: You must set `enableLocalPlatform` to `false` so that the local platform deployer is never used.

NOTE: The `deleteRoutes` deployment setting is `false` so that "`v2`" of an application has the same route as "`v1`".
Otherwise, undeploying "`v1`" removes the route.

You can also run the Skipper server locally and deploy to Cloud Foundry.
In this case, it is more convenient to specify the configuration in a `skipper.yml` file and start the server with the `--spring.config.additional-location=skipper.yml` option.

If you use `cf push` to deploy Skipper, a Cloud Foundry manifest is more appropriate to use.
You can modify the following sample manifest.yml to fit your needs:

[source,yml,options="nowrap"]
----
applications:
- name: mlp-skipper
  host: mlp-skipper
  memory: 1G
  disk_quota: 1G
  timeout: 180
  instances: 1
  buildpack: java_buildpack
  path: spring-cloud-skipper-server.jar
env:
    SPRING_APPLICATION_NAME: mlp-skipper
    SPRING_PROFILES_ACTIVE: cloud
    JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{enabled: false}'
    SPRING_CLOUD_SKIPPER_SERVER_ENABLELOCALPLATFORM: false
    SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[pws]_CONNECTION_URL: https://api.run.pivotal.io
    SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[pws]_CONNECTION_ORG: myOrgQA
    SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[pws]_CONNECTION_SPACE: mySpaceQA
    SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[pws]_CONNECTION_DOMAIN: cfapps.io
    SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[pws]_CONNECTION_USERNAME: cf-qa@example.com
    SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[pws]_CONNECTION_PASSWORD: drowssap
    SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[pws]_CONNECTION_SKIP_SSL_VALIDATION: false
    SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[pws]_DEPLOYMENT_DELETE_ROUTES: false
    SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[pws]_DEPLOYMENT_SERVICES: rabbitmq
services:
- mysqlboost
----

NOTE: In the preceding manifest, we bound the application to the `mysqlboost` service.
If you do not specify a service, the server uses an embedded database.

NOTE: As of Skipper 2.0, you must disable Spring Auto-reconfiguration and set the profile to `cloud`.

NOTE: You must set `SPRING_CLOUD_SKIPPER_SERVER_ENABLELOCALPLATFORM` to `false` so that the local platform deployer is never used.

NOTE: You must set `SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[pws]_DEPLOYMENT_DELETE_ROUTES: false` so that "`v2`" of an application has the same route as "`v1`".
Otherwise, undeploying "`v1`" removes the route.

NOTE: You must set `SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[pws]_DEPLOYMENT_SERVICES` property that binds the specified services to each of the deployed applications.

You can find information on the deployment properties that you can configure in https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/blob/master/src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeploymentProperties.java[CloudFoundryDeploymentProperties].

When starting the Skipper shell on your local machine, it tries to connect to the Server at the default location of `http://localhost:7577/api`.
Use the shell's `--spring.cloud.skipper.client.serverUri` command line option to specify the location of the server.
You can alternatively use the `config` interactive shell command to set the server location, as follows:

[source,bash]
----
server-unknown:>skipper config --uri https://mlp-skipper.cfapps.io/api
Successfully targeted https://mlp-skipper.cfapps.io/api
skipper:>
----

=== Database Connection Pool
As of Skipper 2.0, the Spring Cloud Connector library is no longer used to create the DataSource.
The library  https://github.com/pivotal-cf/java-cfenv[java-cfenv] is now used which allows you to set https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-connect-to-production-database[Spring Boot properties] to configure the connection pool.

[[skipper-installation-cloudfoundry-maximum-disk-quota-configuration]]
=== Maximum Disk Quota
By default, every application in Cloud Foundry starts with 1G disk quota and this can be adjusted to a default maximum of
2G. The default maximum can also be overridden up to 10G by using Pivotal Cloud Foundry's (PCF) Ops Manager GUI.

This configuration is relevant for Spring Cloud Skipper because every deployment is composed of applications
(typically Spring Boot uber-jar's), and those applications are resolved from a remote maven repository. After resolution,
the application artifacts are downloaded to the local Maven Repository for caching and reuse. With this happening in the background,
the default disk quota (1G) can fill up rapidly, especially when we experiment with streams that
are made up of unique applications. In order to overcome this disk limitation and depending
on your scaling requirements, you may want to change the default maximum from 2G to 10G. Let's review the
steps to change the default maximum disk quota allocation.

From PCF's Ops Manager, select the "`Pivotal Elastic Runtime`" tile and navigate to the "`Application Developer Controls`" tab.
Change the "`Maximum Disk Quota per App (MB)`" setting from 2048 (2G) to 10240 (10G). Save the disk quota update and click
"`Apply Changes`" to complete the configuration override.

[[configuration-cloudfoundry-managing-disk-utilization]]
=== Managing Disk Use

Even when configuring Skipper to use 10G of space, there is the possibility of exhausting
the available space on the local disk.
If you deploy the Skipper by using the default `port` health check type, you must explicitly monitor the disk space on the server in order to avoid running out space.
If you deploy the server by using the `http` health check type (see the next example), the server is restarted if there is low disk space.
This is due to Spring Boot's link:https://github.com/spring-projects/spring-boot/blob/v1.5.14.RELEASE/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/health/DiskSpaceHealthIndicator.java[Disk Space Health Indicator].
You can link:https://docs.spring.io/spring-boot/docs/1.5.14.RELEASE/reference/htmlsingle/#common-application-properties[configure] the settings of the Disk Space Health Indicator by using the properties that have the `management.health.diskspace` prefix.

For version 1.7, we are investigating the use of link:https://docs.cloudfoundry.org/devguide/services/using-vol-services.html[Volume Services] for the server to store `.jar` artifacts before pushing them to Cloud Foundry.

The following example shows how to deploy the `http` health check type to an endpoint called `/management/health`:

====
[source]
----
---
  ...
  health-check-type: http
  health-check-http-endpoint: /management/health
----
====

[[skipper-installation-kubernetes]]
== Installing on Kubernetes

A docker image, named `springcloud/spring-cloud-skipper-server`, is available for Skipper server in dockerhub.
You can use this image to run the Skipper server in Kubernetes.


[[skipper-kubernetes-configuration]]
=== Kuberenetes configuration


The following example YAML file configures two accounts, named `k8s-dev` and `k8sqa`, on a Kubernetes cluster.

```
spring:
  cloud:
    skipper:
      server:
        platform:
          kubernetes:
            accounts:
              k8s-dev:
                namespace: devNamespace
                cpu: 4
              k8s-qa:
                namespace: qaNamespace
                memory: 1024m
```

The accounts correspond to different namespaces.
We are investigating how to support connecting to different Kubernetes clusters.

You can find more information on the deployment properties that you can configure in https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/master/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesDeployerProperties.java[KubernetesDeployerProperties]

[[skipper-database-configuration]]
== Database configuration

Spring Cloud Skipper uses a relational database to store metadata.
We use https://flywaydb.org/[Flyway] to bootstrap and then migrate the database as the product evolves.
We currently provide schemas for the following databases: H2, HSQLDB, MySQL, PostgreSQL, Microsoft SQL Server, Oracle 12, and IBM DB2.

The JDBC drivers for MySQL (through the MariaDB driver), HSQLDB, PostgreSQL, and SQL Server, along the embedded H2 database, are bundled with the server jar.
If you  use any other database, the corresponding JDBC driver jar needs to be on the classpath of the server.
If not specified, the server starts with the embedded in-memory H2 database.

The database properties can be passed as environment variables or command-line arguments to the Server.


NOTE: Make sure that you configure the correct `flyway.schemas` for DB2 and SQL Server. Otherwise, Flyway tries to create its `schema_version` table on the default schema for a connection, which could be different than the schema with which your credentials are associated.
See the https://flywaydb.org/documentation/[Flyway documentation] for more options.

The following listings show some examples:

```
export spring_datasource_url=jdbc:postgresql://localhost:5432/mydb
export spring_datasource_username=myuser
export spring_datasource_password=mypass
export spring_datasource_driver-class-name="org.postgresql.Driver"
```

* *MySQL*
[source,bash,subs=attributes]
----
java -jar spring-cloud-skipper-server-{project-version}.jar \
    --spring.datasource.url=jdbc:mysql:<db-info> \
    --spring.datasource.username=<user> \
    --spring.datasource.password=<password> \
    --spring.datasource.driver-class-name=org.mariadb.jdbc.Driver &
----

* *PostgreSQL*
[source,bash,subs=attributes]
----
java -jar spring-cloud-skipper-server-{project-version}.jar \
    --spring.datasource.url=jdbc:postgresql:<db-info> \
    --spring.datasource.username=<user> \
    --spring.datasource.password=<password> \
    --spring.datasource.driver-class-name=org.postgresql.Driver &
----

* *HSQLDB*
[source,bash,subs=attributes]
----
java -jar spring-cloud-skipper-server-{project-version}.jar \
    --spring.datasource.url=jdbc:hsqldb:mem:<db-info> \
    --spring.datasource.username=sa \
    --spring.datasource.password= \
    --spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver &
----

* *Microsoft SQL Server*
[source,bash,subs=attributes]
----
java -jar spring-cloud-skipper-server-{project-version}.jar \
    --spring.datasource.url=jdbc:sqlserver://<db-info>;database=<database-name> \
    --spring.datasource.username=<user> \
    --spring.datasource.password=<password> \
    --flyway.schemas=<database-name> \
    --spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver &
----

* *Oracle*
[source,bash,subs=attributes]
----
java -jar spring-cloud-skipper-server-{project-version}.jar \
    --spring.datasource.url=jdbc:oracle:thin:<user>/<password>@<db-address>/<service-id> \
    --spring.datasource.username=<user> \
    --spring.datasource.password=<password> \
    --spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver &
----

* *IBM DB2*
[source,bash,subs=attributes]
----
java -jar spring-cloud-skipper-server-{project-version}.jar \
    --spring.datasource.url=jdbc:db2:thin://<db-info>/<db-name> \
    --spring.datasource.username=<user> \
    --spring.datasource.password=<password> \
    --flyway.schemas=<db-name> \
    --spring.datasource.driver-class-name=com.ibm.db2.jcc.DB2Driver &
----
