[[skipper-installation]]
= Using Skipper

[[skipper-installation-local]]
== Installing on a local machine

=== Local Platform configuration

Here is an example YAML file to configure two local deployer accounts named `localDev` and `localDevDebug`
```
spring:
  cloud:
    skipper:
      server:
        platform:
          local:
            accounts:
              localDev:
                shutdownTimeout: 60
                javaOpts: "-Dtest=foo"
              localDevDebug:
                javaOpts: "-Xdebug"
```

The key-value pairs that follow the name of the account are `javaCmd`, `workingDirectoriesRoot`, `deleteFilesOnExit`, `envVarsToInherit`, `shutdownTimeout`, `javaOpts`, and `useSpringApplicationJson`.  More information can be found in the JavaDocs for https://github.com/spring-cloud/spring-cloud-deployer-local/blob/master/spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalDeployerProperties.java[LocalDeployerProperties].

[[skipper-installation-cloudfoundry]]
== Installing on Cloud Foundry

=== Cloud Foundry configuration

Here is an example YAML file to configure two Cloud Foundry accounts named `cf-dev` and `cf-qa`

```
spring:
  cloud:
    skipper:
      server:
        platform:
          cloudfoundry:
            accounts:
              cf-dev:
                connection:
                  url: https://api.run.pivotal.io
                  org: myOrg
                  space: mySpace
                  domain: cfapps.io
                  username: cf-dev@example.com
                  password: drowssap
                  skipSslValidation: false
                deployment:
                  memory: 2048m
                  disk: 2048m
                  services: rabbit
              cf-qa:
                connection:
                  url: https://api.run.pivotal.io
                  org: myOrgQA
                  space: mySpaceQA
                  domain: cfapps.io
                  username: cf-qa@example.com
                  password: drowssap
                  skipSslValidation: true
                deployment:
                  memory: 1024m
                  disk: 1024m
                  services: rabbitQA

```
[[skipper-installation-kubernetes]]
== Installing on Kubernetes

There is not yet a docker image for Skipper.  In the meantime, you can run Skipper locally and depoy to Kubernetes

[skipper-kubernetes-configuration]
=== Kuberenetes configuration


Here is an example YAML file to configure two accounts named `k8s-dev` and `k8sqa` on a Kubernetes cluster that correspond to different namespaces.  We are investigating how to support connecting to different Kubernetes clusters.

```
spring:
  cloud:
    skipper:
      server:
        platform:
          kubernetes:
            accounts:
              k8s-dev:
                namespace: devNamespace
                cpu: 4
              k8s-qa:
                namespace: qaNamespace
                memory: 1024m
```

=== Using local instance of Skipper to Deploy to Kubernetes

TBD