[[overview]]
= Spring Cloud Skipper Overview

Skipper is a lightweight tool that allows you to discover Spring Boot applications and manage their lifecycle on multiple Cloud Platforms.  You can use Skipper standalone or integrate it with Continuous Integration pipelines to help implement the practice of  Continuous Deployment.

Skipper consists of a server application that exposes a HTTP API. A shell application provides easy to use <<skipper-commands,commands>> to
interact with the server.  The server uses a database to store state.  Documentation to call the HTTP API is
available in the <<api-guide>>.

Applications in Skipper are bundled as packages which contain a templated configuration file and a default set of values that are used to fill in the template. You can override these defaults when installing or upgrading a package. Skipper provides a means to orchestrate the upgrade/rollback procedure of applications between different versions, taking the minimal set of actions to bring the system to the desired state.

Skipper's design is influenced by a large number of projects in the Kubernetes ecosystem that perform resource templating and/or orchestration, hence the nautically inspired project name Skipper.  In particular, https://github.com/kubernetes/helm[Helm]'s approach to present a user with familiar `apt-get` or `brew` like installation experience was a big influence.

== Features

The main features are:

* Define multiple platform accounts where Spring Boot applications can be deployed..  Supported platforms are Local, Cloud Foundry, and Kubernetes.
* Substitute variables in Mustache templated files that describe how to deploy applications to a platform.
* Search Package Repositories for existing applications.
* Upgrade/Rollback a package based on a simple blue/green workflow.
* Store the history of resolved template files (aka 'application manifests') which represent the final description of what has been deployed to a platform for a specific release.
* Use via a standalone interactive shell or web API.

== Concepts
The main concepts are Platforms, Packages, Repositories, Releases and Release Workflows.

*Platforms* are where your apps run.  For the first release of Skipper, support for deploying applications to platforms is provided by the https://github.com/spring-cloud/spring-cloud-deployer[Spring Cloud Deployer] family of libraries.
This allows Skipper to deploy Spring Boot applications to Cloud Foundry, Kubernetes and your local machine.
You can configure a single Skipper server to deploy to multiple platforms, with each platform account is identified
by a unique name.

NOTE: The Spring Cloud Deployer libraries for Apache YARN, Apache Mesos, Redhat Openshift and Hashicorp Nomad were not
bundled with Skipper in 1.0 M2.  Skipper 1.0 M2 has only been tested using the local, Cloud Foundry and Kubernetes Deployers.

*Packages* defines the basic recipe for installing an application.
A package can define a single application or it can define a group of applications.
It contains descriptive metadata, the location of the Spring Boot uberjar and the default application or deployment
properties.
The location of the uberjar can be a Maven repository, docker registry, file location, or http location.
A package is a collection of Yaml files that are zipped up into a file with a naming convention such as name-version.zip, e.g. myapp-1.0.3.zip.

*Repositories* are where package metadata and zip files are hosted.  Repositories and be 'local' or 'remote'.
A remote repository is the one that is only accessible via http.
Any arbitrary web app that serves up files off a file system can be used to host a remote repository as long as certain directory and file naming conventions are followed.
A local repository is managed by the Skipper server and backed by a database. Skipper lets you search for packages that are hosted in repositories.

*Releases* are created in Skipper after you install, upgrade or rollback a package.
A release has a name and you provide that name to perform operations against the release such as upgrading, rolling back and deleting applications. The release contains the fully resolved template files (aka 'application manifests') that represent the final description of what has been deployed to the platform. You can also query for releases to discover the state of packages that have been installed and retrieve the application manifests for a specific release.

*Release Workflows* are the steps taken to upgrade or rollback an application from one version to another. In Skipper terms, it is how we go from one Release to another on a Platform.  Note, an upgrade may keep the same version, but instead update applications properties.

