[[preface]]
= Preface

[[skipper-documentation-about]]
== About the Documentation

The documentation for this release is available in https://docs.spring.io/spring-cloud-skipper/docs/{project-version}/reference/htmlsingle[HTML].

The latest copy of the Spring Cloud Skipper reference guide can be found {spring-cloud-skipper-docs-current}[here].

Copies of this document may be made for your own use and for
distribution to others, provided that you do not charge any fee for such copies and
further provided that each copy contains this Copyright Notice, whether distributed in
print or electronically.

[[skipper-documentation-getting-help]]
== Getting Help
If you are having trouble with Spring Cloud Skipper, we would like to help!

* Ask a question. We monitor https://stackoverflow.com[stackoverflow.com] for questions
  tagged with https://stackoverflow.com/tags/spring-cloud-skipper[`spring-cloud-skipper`].
* Reach out to us on https://gitter.im/spring-cloud/spring-cloud-skipper[gitter].
* Report bugs with Spring Cloud Skipper at https://github.com/spring-cloud/spring-cloud-skipper/issues.

NOTE: All of Spring Cloud Skipper is open source, including the documentation! If you find problems
with the docs or if you want to improve them, please {github-code}[get involved].
