[[preface]]
= Preface

[[skipper-documentation-about]]
== About the documentation
The Spring Cloud Skipper reference guide is available in {spring-cloud-skipper-docs}/html[html]. The latest copy
is available at {spring-cloud-skipper-docs-current}.

Copies of this document may be made for your own use and for
distribution to others, provided that you do not charge any fee for such copies and
further provided that each copy contains this Copyright Notice, whether distributed in
print or electronically.

[[skipper-documentation-getting-help]]
== Getting help
Having trouble with Spring Cloud Skipper, We'd like to help!

* Ask a question - we monitor http://stackoverflow.com[stackoverflow.com] for questions
  tagged with http://stackoverflow.com/tags/spring-cloud-skipper[`spring-cloud-skipper`].
* Report bugs with Spring Cloud Skipper at https://github.com/spring-cloud/spring-cloud-skipper/issues.

NOTE: All of Spring Cloud Skipper is open source, including the documentation! If you find problems
with the docs; or if you just want to improve them, please {github-code}[get involved].
