[[three-hour-tour]]
= Using Skipper

This section is the 'three hour tour' of Skipper.  It describes how to configure and use the main feature set of Skipper in detail.
 We will cover, platforms, packages, repositories, releases and update strategies.

Feel free to reach out on https://gitter.im/spring-cloud/spring-cloud-skipper[Gitter] for help and ask questions on https://stackoverflow.com/questions/tagged/spring-cloud-skipper[Stack Overflow].
Issues can be filed on https://github.com/spring-cloud/spring-cloud-skipper/issues[Github issues].

[[using-shell]]
== Shell Modes

The shell can be started either in interactive or non-interactive mode.
 In the case of the non-interactive mode, command line arguments are executed as Skipper commands and then the shell exits.
If there are any arguments that do not have the prefix `spring.cloud.skipper.client`, they will be considered as skipper commands to execute.


For example,

[source,bash,subs=attributes]
```
java -jar spring-cloud-skipper-shell-{project-version}.jar --spring.cloud.skipper.client.serverUri=http://localhost:9123/api
```
Will bring up the interactive shell and connect to `http://localhost:9123/api`.
However, the command

[source,bash,subs=attributes]
```
$ java -jar spring-cloud-skipper-shell-{project-version}.jar --spring.cloud.skipper.client.serverUri=http://localhost:9123/api search
```

Will connect to `http://localhost:9123/api`, execute the `search` command and then exit.

A more common use case would be to update a package from within a CI job.  For example, in a Jenkins Stage.

[source,groovy]
```
stage ('Build') {
    steps {
        checkout([
            $class: 'GitSCM',
            branches: [
                [name: "*/master"]
            ],
            userRemoteConfigs: [
                [url: "https://github.com/markpollack/skipper-samples.git"]
            ]
        ])
        sh '''
            VERSION="1.0.0.M1-$(date +%Y%m%d_%H%M%S)-VERSION"
            mvn org.codehaus.mojo:versions-maven-plugin:2.3:set -DnewVersion="${VERSION}"
            mvn install
            java -jar /home/mpollack/software/skipper.jar upgrade --package-name helloworld --release-name helloworld-jenkins --properties version=${VERSION}
        '''
    }
}
```


[[using-platforms]]
== Platforms

Skipper supports deploying to multiple platforms.
The platforms included are Local, Cloud Foundry and Kubernetes.
For each platform, you can configure multiple accounts.
Each `account name` must be globally unique across all platforms.

Usually different `accounts` will correspond to a different orgs/spaces for Cloud Foundry and different namespaces for a single Kubernetes cluster.

Platforms are defined using Spring Boot's https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html[Externalized Configuration] feature.
To simplify setup in 1.0 M2, if a local platform account is not defined in your configuration, Skipper will create a `local` deployer implementation named `default`.

You can make use of the http://cloud.spring.io/spring-cloud-static/spring-cloud-config/1.3.3.RELEASE/multi/multi__spring_cloud_config_server.html#_encryption_and_decryption[Encryption and Decryption] features of Spring Cloud Config as one way to secure credentials.

Distinct from where Skipper will deploy application, you can also run the Skipper server itself on a platform.  Installation on other platforms is covered in the <<skipper-installation>> section.

Here is example YAML file showing configuration of all three platforms

----
spring:
  cloud:
    skipper:
      server:
        platform:
          local:
            accounts:
              localDevDebug:
                javaOpts: "-Xdebug"
          cloudfoundry:
            accounts:
              cf-dev:
                connection:
                  url: https://api.run.pivotal.io
                  org: scdf-ci
                  space: space-mark
                  domain: cfapps.io
                  username: <your-username>
                  password: <your-password>
                  skipSslValidation: false
                deployment:
                  deleteRoutes: false
          kubernetes:
            accounts:
              minikube:
                namespace: default
----

The properties available for each platform can be found in these classes

* https://github.com/spring-cloud/spring-cloud-deployer-local/blob/master/spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalDeployerProperties.java[LocalDeployerProperties].
* https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/blob/master/src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeploymentProperties.java[CloudFoundryDeploymentProperties] for `deployment:` and https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/blob/master/src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryConnectionProperties.java[CloudFoundryConnectionProperties] for the `connection:`.
* https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/master/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesDeployerProperties.java[KubernetesDeployerProperties]

[[using-packages]]
== Packages

Packages contain all the necessary information to install your application or group of applications.
The approach to decribing the applications is to use a YAML file that provides all the necessary information to help facilitate searching for your application hosted in a Package Registry and to install your application to a platform.

To make it easy to customize a package, the YAML files are templated.  The final version of the YAML file, with all values substituted is known as the release `manifest`.
Skipper currently understands how to deploy applications based off a YAML file that contains the information needed for a Spring Cloud Deployer implementation to deploy an application.  It describes, where to find the application (either a http, maven or docker location) , application properties (think Spring Boot `@ConfigurationProperties`), an deployment properites (e.g. how much memory to use).

[[using-package-format]]
=== Package Format

A package is a collection of YAML files that are zipped up into a file with the naming convention
`[PackageName]-[PackageVersion].zip` for example: `mypackage-1.0.0.zip`

A package can define a single application or a group of applications.

The single application package file, `mypackage-1.0.0.zip` when unzipped, should have the following directory structure.

----
mypackage-1.0.0
├── package.yml
├── templates
│   └── template.yml
└── values.yml
----

The `package.yml` file contains metadata about the package and is used to support Skipper's search functionality.
The `template.yml` file contains placeholders for values that are specified in the `values.yml` file.
When installing a package, placeholder values can also be specified and they would override the values in the `values.yml` file.
The templating engine that Skipper uses https://github.com/samskivert/jmustache[JMustache].
The YAML files can have either `.yml` or `.yaml` extensions.

The files https://github.com/markpollack/skipper-sample-repository/blob/master/src/main/resources/static/repository/experimental/helloworld/helloworld-1.0.0.zip[helloworld-1.0.0.zip] or https://github.com/markpollack/skipper-sample-repository/blob/master/src/main/resources/static/repository/experimental/helloworld-docker/helloworld-docker-1.0.0.zip[helloworld-docker-1.0.0.zip] are good examples to use as a basis to create your own package 'by-hand'.

The source code for the helloword sample can be found https://github.com/markpollack/skipper-samples[here].

[[using-package-format-multiple-apps]]
=== Package with multiple applications

A package can contain a group of applications bundled in it.
In those cases, the structure of the package would look like this:

----
mypackagegroup-1.0.0
├── package.yml
├── packages
│   ├── app1
│   │   ├── package.yml
│   │   ├── templates
│   │   │   └── log.yml
│   │   └── values.yml
│   └── app2
│       ├── package.yml
│       ├── templates
│       │   └── time.yml
│       └── values.yml
└── values.yml
----

In the above, the `mypackagegroup` would still have its own `package.yml`, `values.yml` to specify the package metadata
 and the values to override.
All the applications inside the `mypackagegroup`  are considered sub-packages and would follow the similar package
structure as the individual packages.
These sub packages need to be specified inside the `packages` directory of the root package `mypackagegroup`.

The file https://github.com/spring-cloud/spring-cloud-skipper/blob/master/spring-cloud-skipper-server-core/src/test/resources/repositories/binaries/test/ticktock/ticktock-1.0.0.zip[ticktock-1.0.0.zip] is a good example to use as a basis for creating your own package 'by-hand'.


[[using-package-metadata]]
=== Package Metadata (package.yml)

The `package.yml` file specifies the package metadata.
A sample package metadata would look like this:

----
# Required Fields
apiVersion: skipper.spring.io/v1
kind: SkipperPackageMetadata
name: mypackage
version: 1.0.0

# Optional Fields
packageSourceUrl: https://github.com/some-mypackage-project/v1.0.0.RELEASE
packageHomeUrl: http://some-mypackage-project/
tags: skipper, mypackage, sample
maintainer: https://github.com/maintainer
description: This is a mypackage sample.
----

*Required Fields:*

* `apiVersion` - 	The Package Index spec version this file is based on
* `kinds` - What type of package system is being used
* `name` -  name of the package
* `version` - version of the package

*Optional Fields:*

* `packageSourceUrl` - 	Location to source code for this package.
* `packageHomeUrl` - The home page of the package
* `tags` -  A comma separated list of tags to be used for searching
* `maintainer` - Who is maintaining this package
* `description` Free form text describing the functionality of the package.  Will generally be shown in search results.
* `sha256` - Hash of package binary  (not yet enforced)
* `iconUrl` - URL for an icon to show for this package.
* `origin` - Free form text describing the origin of this package, for example your company name.

NOTE: Currently, the package search functionality is only a wildcard match against the name of the package.

A Package Repository exposes an `index.yml` file that contains multiple metadata documents, separated by the standard three dash notation `---` to separate the documents.  For example http://skipper-repository.cfapps.io/repository/experimental/index.yml[index.yml].

[[using-package-template-files]]
=== Package Templates (template.yml)

The `template.yml` file in a package structure such as

----
mypackage-1.0.0
├── package.yml
├── templates
│   └── template.yml
└── values.yml
----

will commonly have the following content:

----
# template.yml
apiVersion: skipper.spring.io/v1
kind: SpringCloudDeployerApplication
metadata:
  name: mypackage
  type: sample
spec:
  resource: maven://org.mysample:mypackage
  resourceMetadata:  maven://org.mysample:mypackage:jar:metadata:{{spec.version}}
  version: {{spec.version}}
  applicationProperties:
    {{#spec.applicationProperties.entrySet}}
    {{key}}: {{value}}
    {{/spec.applicationProperties.entrySet}}
  deploymentProperties:
    {{#spec.deploymentProperties.entrySet}}
    {{key}}: {{value}}
    {{/spec.deploymentProperties.entrySet}}
----

The `apiVersion`, `kind` and `spec.resource` are required.

The `spec.resource` and `spec.version` define where the application executable is located.
The `spec.resourceMetadata` field defines where a https://docs.spring.io/spring-boot/docs/current/reference/html/configuration-metadata.html[Spring Boot Configuration meta-data] jar is located that contains
configuration properties of the application.
This is either a Spring Boot uberjar hosted under a http endpoint or a maven or docker repository.
The template placeholder `{{spec.version}}` so that the version of a specific application can be easily upgraded without having to create a new package .zip file.

The `resource` is `http://` or a `maven://` or `docker:` based.  The format for specifying a `resource` is shown below.

==== HTTP Resources

----
spec:
  resource: http://example.com/app/hello-world
  version: 1.0.0.RELEASE
----

There is a naming convention that must be followed for HTTP based resource so that Skipper can assemble a full URL from the `resource` and `version` field and also parse the version number given the URL.
The above `spec` will reference a URL at `http://example.com/app/hello-world-1.0.0.RELEASE.jar`.
The `resource` and `version` fields should not have any numbers after the `-` character.

==== Docker Resources

----
spec:
  resource: docker:springcloud/spring-cloud-skipper-samples-helloworld
  version: 1.0.0.RELEASE
----

The mapping to docker registry names is

----
spec:
  resource: docker:<user>/<repo>
  version: <tag>
----


==== Maven Resources

----
spec:
  resource: maven://org.springframework.cloud.samples:spring-cloud-skipper-samples-helloworld:1.0.0.RELEASE
  version: 1.0.0.RELEASE
----

The mapping to maven artifact names is
----
spec:
  resource: maven://<maven-group-name>:<maven-artifact-name>
  version:<maven-version>
----

There is only one setting to specify with maven repositories to search.  This applies across all platform accounts.  By default the configuration:

----
maven:
  remoteRepositories:
    springRepo: https://repo.spring.io/libs-snapshot
----

is used.  You can specify other entries and also specify proxy properties.  This is currently best documented https://docs.spring.io/spring-cloud-dataflow/docs/1.3.0.M2/reference/htmlsingle/#getting-started-maven-configuration[here]. Essentially, this needs to be set a property in your launch properties or `manifest.yml` (when pushing to PCF) like so:

----
# manifest.yml
...
env:
    MAVEN_REMOTE_REPOSITORIES_{{REPOSITORY_NAME}}_URL: https://repo.spring.io
...
----

The metadata is used to help search for applications after they have been installed and is not available in Skipper 1.0 M2.

Currently, only `SpringCloudDeployerApplication` kind is supported which means the applications can be deployed into the target platforms only using their corresponding Spring Cloud Deployer implementations (CF, Kubernetes Deployer etc.).

The `spec` contains the resource specification and the properties for the package.

The `resource` represents the resource URI to download the application from. This would typically be a maven
co-ordinate or a docker image URL.

The `SpringCloudDeployerApplication` kind of application can have `applicationProperties` and `deploymentProperties` as the
configuration properties.

The application properties correspond to the properties for the application itself.

The deployment properties correspond to the properties for the deployment operation performed by Spring Cloud Deployer implementations.

NOTE: The `name` of the template file can be anything as all the files under `templates` directory are loaded to
apply the template configurations.

[[using-package-values]]
=== Package Values (values.yml)

The `values` YAML file contains the default values for any of the keys specified in the template files.

For instance, in a package that defines one application, the format is

----
version: 1.0.0.RELEASE
spec:
  applicationProperties:
    server.port: 9090
----

If the package defines multiple applications, provide the name of the package in the top level YML section to scope the `spec` section.  That is, given a multiple application package with the layout

----
ticktock-1.0.0/
├── packages
│   ├── log
│   │   ├── package.yml
│   │   └── values.yml
│   └── time
│       ├── package.yml
│       └── values.yml
├── package.yml
└── values.yml

----
A top level `values.yml` file

----
#values.yml

hello: world

time:
  appVersion: 1.3.0.M1
  deployment:
    applicationProperties:
      log.level: WARN
      trigger.fixed-delay: 1
log:
  deployment:
    count: 2
    applicationProperties:
      log.level: WARN
      log.name: skipperlogger
----

Would set `hello` as a variable available to be used as a placeholder in the `packages\log\values.yml` file and the `packages\time\values.yml`.  However, the YML section under `time:` is applied only to the `packages\time\values.yml` file and the YML section under `log:` is applied only to the `packages\time\values.yml` file.

[[using-package-upload]]
=== Package Upload

After creating the package in the above structure, we can compress it in a zip file with the name
[PackageName]-[PackageVersion].zip e.g. mypackage-1.0.0.zip

For instance, the package directory would look like this before compression:

----
mypackage-1.0.0
├── package.yml
├── templates
│   └── template.yml
└── values.yml
----
This zip file can be uploaded into one of the local repositories of Skipper server.
By default, Skipper server has the local repository with the name `local`.

Using the Skipper Shell, we can upload the package zip into Skipper server's one of the local repositories.

[source,bash,options="nowrap"]
----
skipper:>upload --path /path-to-package/mypackage-1.0.0.zip
Package uploaded successfully:[mypackage:1.0.0]
----

If no `--repo-name` is set, the `upload` command will use `local` as the repository to upload.

[source,bash,options="nowrap"]
----
skipper:>search
╔═════════════════╤═══════╤════════════════════════════════════════════════════════════════════════════════╗
║      Name       │Version│                                  Description                                   ║
╠═════════════════╪═══════╪════════════════════════════════════════════════════════════════════════════════╣
║helloworld       │1.0.0  │The app has two endpoints, /about and /greeting in English.  Maven resource.    ║
║helloworld       │1.0.1  │The app has two endpoints, /about and /greeting in Portuguese.  Maven resource. ║
║helloworld-docker│1.0.0  │The app has two endpoints, /about and /greeting in English.  Docker resource.   ║
║helloworld-docker│1.0.1  │The app has two endpoints, /about and /greeting in Portuguese.  Docker resource.║
║mypackage        │1.0.0  │This is a mypackage sample                                                      ║
╚═════════════════╧═══════╧════════════════════════════════════════════════════════════════════════════════╝
----

[[using-package-create]]
=== Creating Your Own Package

In this section, we will try to create a package that can be deployed using Spring Cloud Deployer implementations.

For this package, we are going to be creating a super simple package and uploading it to our local machine.

To get started creating your own package, create a folder following the naming convention (`[package-name]-[package-version]`), in our case it will be `demo-1.0.0`.
In this directory, create empty files `values.yml`, `package.yml` and a `templates` directory.
In the `templates` directory create an empty `template.yml` file.

Go into the `package.yml` where we are going to specify the package metadata, for this app we are only going to be filling the minimum values possible:

----
# package.yml

apiVersion: skipper.spring.io/v1
kind: SkipperPackageMetadata
name: demo
version: 1.0.0
description: Greets the world!
----

Importantly here, ensure that your `name` and `version` matches the `name` and `version` in your folder name or you will get an error.

Next, open up your `templates/template.yml`. Here we are going to be specifying the actual information about your package and most importantly setting default values.
In the `template.yml`, copy the template for the kind `SpringCloudDeployerApplication` from the above sample.

----
# templates/template.yml

apiVersion: skipper.spring.io/v1
kind: SpringCloudDeployerApplication
metadata:
  name: demo
spec:
  resource: maven://org.springframework.cloud.samples:spring-cloud-skipper-samples-helloworld
  version: {{version}}
  applicationProperties:
    {{#spec.applicationProperties.entrySet}}
    {{key}}: {{value}}
    {{/spec.applicationProperties.entrySet}}
  deploymentProperties:
    {{#spec.deploymentProperties.entrySet}}
    {{key}}: {{value}}
    {{/spec.deploymentProperties.entrySet}}
----

Simply, this specifies our application name is `demo`, and finds our package in maven and we can specify a `version`,
`applicationProperties` and `deploymentProperties` in our `values.yml`. So lets do that.

----
# values.yml

# This is a YAML-formatted file.
# Declare variables to be passed into your templates
version: 1.0.0.RELEASE
spec:
  applicationProperties:
    server.port: 8100
----

This will set out `version` to `1.0.0.RELEASE` and also set the `server.port=8100` as one of the application properties.
When the Skipper Package reader resolves these values by merging the `values.yml` against the template, the resolved values would look like this:

----
# hypothetical template.yml

apiVersion: skipper.spring.io/v1
kind: SpringCloudDeployerApplication
metadata:
  name: demo
spec:
  resource: maven://org.springframework.cloud.samples:spring-cloud-skipper-samples-helloworld
  version: 1.0.0.RELEASE
  applicationProperties:
    server.port: 8100
  deploymentProperties:
----

The reason to use `values.yml` instead of entering the values directly is that it allows you to overwrite the values at run time using the `--file` or `--properties` flags.

We have now finished making our file, we now have to zip it up. The easiest way to do is the `zip -r` command line command. You should see something like:

----
$ zip -r demo-1.0.0.zip demo-1.0.0/
  adding: demo-1.0.0/ (stored 0%)
  adding: demo-1.0.0/package.yml (deflated 14%)
  adding: demo-1.0.0/templates/ (stored 0%)
  adding: demo-1.0.0/templates/template.yml (deflated 55%)
  adding: demo-1.0.0/values.yml (deflated 4%)
----

Armed with our zipped file and the path to it, we can head to skipper and use the `upload` command:

----
skipper:> upload --path /Users/path-to-your-zip/demo-1.0.0.zip
Package uploaded successfully:[demo:1.0.0]
----

Now you can search for it as shown above, then install it!

----
skipper:>install --package-name demo --package-version 1.0.0 --release-name demo
Released demo. Now at version v1.
----

Congratulations! You have now created, packaged, uploaded and installed your own Skipper Package!

== Repositories

Repositories are where package metadata and package .zip files are hosted.  Repositores can be local or remote, were local means backed by Skipper's relational database and remote means a filesystem exposed over http.

When registering a remote registry, for example, the `experimental` one that is currently defined by default in addition to one named local` use the following format:

----
spring
  cloud:
    skipper:
      server:
        packageRepositories:
          -
            name: experimental
            url: http://skipper-repository.cfapps.io/repository/experimental
            description: Experimental Skipper Repository
            repoOrder: 0
          -
            name: local
            url: http://${spring.cloud.client.hostname}:7577
            local: true
            description: Default local database backed repository
            repoOrder: 1

----

The `repoOrder` determines which repository will serve up a package if one with the same name is registered in two or more repositories.

The directory structure assumed for a remote repository is the registered `url` value followed by the package name and then the zip file name., e.g. `http://skipper-repository.cfapps.io/repository/experimental/helloworld/helloworld-1.0.0.zip` for the package `helloworld` with the version `1.0.0`.  Directly under the registered `url` is expected to be a file named `index.yml`, e.g. http://skipper-repository.cfapps.io/repository/experimental/index.yml.  This contains the package metadata for all the packages hosted by the repository.

It is up to you to update the `index.yml` file 'by-hand' for remote repositories.

'Local' repositories are backed by Skipper's database.  In the 1.0 M2 release they does not expose the index.yml or the .zip files under a filesystem like URL structure as with remote repositories. This will be provided in the next version.  However, on the positive side, you can upload packages to a local repository and don't need to maintain an index file.  See the skipper command section for information on creating local repositories.

A good example that shows using a Spring Boot web application with static resources to host a Repository can be found https://github.com/markpollack/skipper-sample-repository[here].  This application is currently running under http://skipper-repository.cfapps.io/repository/experimental.



