== Skipper Integration Tests
This modules hosts integration tests pipeline for concourse CI.

=== Introduction
Foundation of this test suite is to run `docker` images via
`docker-compose` which gives as a way to build relatively static and
reliable configs due to internal networking `docker-compose` setups.
For example we can define image for a database with name _mysql_ and
then from server image reference into that JDBC uri using hostname
`mysql`.

- _ci_ contains concourse relates configs, scripts and images.
- _custom-apps_ contains custom skipper server builds bundling
  additional JDBC drivers.
- _docker-images_ contains additional images not available from
  dockerhub we need during a tests. These images may contain something
  we can't expose publicly due to licensing, i.e. oracle.
- _spring-cloud-skipper-acceptance-core_ contains base system for
  integration tests, i.e. `junit5` integration into `docker-compose`.
- _spring-cloud-skipper-acceptance-tests_ contains actual acceptance
  tests.
- _spring-cloud-skipper-acceptance-image-*_ contains images we only
  need locally within a build and which doesn't need to go into repos.
  Also these are mosly used to build images out from fatjars and it's
  more reliable to have i.e. snapshot fatjar to converted into image
  and runtime.


=== Running Test Suite Locally
Pipeline is using spesific docker and compose versions(for other versions mileage may vary, try it):

- DOCKER_VERSION=17.12.0-ce
- DOCKER_COMPOSE_VERSION=1.18.0

You need to be able to login to artifactory to fetch custom private images.
Get your artifactory username and encrypted password.
```
docker login springsource-docker-private-local.jfrog.io
# or if you need to pass those is from command line(gives you sec warning)
docker login -u <artifactoryUsername> -p <artifactoryPassword> springsource-docker-private-local.jfrog.io
```

You need same credentials to authenticate with private maven repo. Either export those into
environment variables or put `artifactoryUsername` and `artifactoryPassword` into
gradle's global parameters file.
```
export ARTIFACTORY_USERNAME=<artifactoryUsername>
export ARTIFACTORY_PASSWORD=<artifactoryPassword>
```

Successful build looks something like:
```
./gradlew clean build

BUILD SUCCESSFUL in 9m 37s
38 actionable tasks: 34 executed, 4 up-to-date
```

=== Deploy Pipeline
This pipeline depends on credentials to be available via `credhub`
associated with `ci.spring.io`.


```
fly --target ci login --team-name spring-cloud-dataflow --concourse-url https://ci.spring.io
fly -t ci set-pipeline -p acceptance-tests -c ci/pipeline.yml -l ci/parameters.yml
```

Jobs in a pipeline in UI are grouped into _Tests_, _CI-Images_ and
_CI-Apps_. This allows to update images outside of a normal tests.
```
$ fly -t ci jobs -p acceptance-tests
name                                  paused  status     next
spring-cloud-skipper-ci-images        no      succeeded  n/a
acceptance-tests                      no      succeeded  n/a
build-skipper-server-with-drivers100  no      succeeded  n/a
build-skipper-server-with-drivers101  no      succeeded  n/a
```

You can trigger these jobs either from UI or from command line:
```
$ fly -t ci trigger-job -j acceptance-tests/build-skipper-server-with-drivers100
```


=== Problems and Other Info
This section contains additional info and how to track problems.

==== Large Oracle Docker Image
Our pre-built oracle image is relatively large(3.5G) and if something
goes wrong when build is pulling out images, it's most likely this.
You may want to pre-pull this image to local cache.
```
docker pull springsource-docker-private-local.jfrog.io/oracle/database-prebuilt:12.2.0.1-se2
```

==== Currently Pulled Images
Here is a list of images pulled either from dockerhub or artifactory:
```
$ docker images
REPOSITORY                                                            TAG                 IMAGE ID            CREATED             SIZE
spring-cloud-skipper-acceptance-image-legacy101                       1.0.1               3c4625ca2596        8 minutes ago       712MB
spring-cloud-skipper-acceptance-image-legacy101                       latest              3c4625ca2596        8 minutes ago       712MB
spring-cloud-skipper-acceptance-image-legacy100                       1.0.0               8efc075a156b        8 minutes ago       712MB
spring-cloud-skipper-acceptance-image-legacy100                       latest              8efc075a156b        8 minutes ago       712MB
spring-cloud-skipper-acceptance-image-drivers101                      latest              3d05f70938b7        8 minutes ago       789MB
spring-cloud-skipper-acceptance-image-drivers100                      latest              1f755c302900        8 minutes ago       789MB
postgres                                                              10                  30121e967865        2 weeks ago         289MB
mysql                                                                 5.6                 079344ce5ebd        2 weeks ago         256MB
springsource-docker-private-local.jfrog.io/oracle/database-prebuilt   12.2.0.1-se2        21085dc2ce49        8 weeks ago         10.1GB
alpine                                                                latest              3fd9065eaf02        2 months ago        4.15MB
java                                                                  8                   d23bdf5b1b1b        14 months ago       643MB
```

