CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE APP_REGISTRATION (
    ID BIGINT NOT NULL,
    OBJECT_VERSION BIGINT,
    DEFAULT_VERSION BOOLEAN,
    METADATA_URI CLOB,
    NAME VARCHAR(255),
    TYPE INTEGER,
    URI CLOB,
    VERSION VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE AUDIT_RECORDS (
    ID BIGINT NOT NULL,
    AUDIT_ACTION BIGINT NOT NULL,
    AUDIT_DATA VARCHAR(2147483647),
    AUDIT_OPERATION BIGINT NOT NULL,
    CORRELATION_ID VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_ON TIMESTAMP,
    PRIMARY KEY (ID)
);
