#!/bin/bash
set -e
if [ ! -d uaa ]; then
  git clone --branch 4.32.0 https://github.com/cloudfoundry/uaa.git
fi
HAS_CRED=$(grep -c -F "credentials" uaa/settings.gradle)
if ((HAS_CRED == 0)); then
  cat ./build-script.gradle.fragment >> uaa/settings.gradle
fi
pushd uaa
  ./gradlew clean :cloudfoundry-identity-uaa:assemble
popd
cp uaa/uaa/build/libs/cloudfoundry-identity-uaa-*.war ./cloudfoundry-identity-uaa.war
