DROP VIEW IF EXISTS AGGREGATE_TASK_EXECUTION;
DROP VIEW IF EXISTS AGGREGATE_TASK_EXECUTION_PARAMS;
DROP VIEW IF EXISTS AGGREGATE_JOB_EXECUTION;
DROP VIEW IF EXISTS AGGREGATE_JOB_INSTANCE;
DROP VIEW IF EXISTS AGGREGATE_TASK_BATCH;
DROP VIEW IF EXISTS AGGREGATE_STEP_EXECUTION;

DROP TABLE IF EXISTS app_registration CASCADE;
DROP TABLE IF EXISTS task_deployment CASCADE;
DROP TABLE IF EXISTS audit_records CASCADE;
DROP TABLE IF EXISTS stream_definitions CASCADE;
DROP TABLE IF EXISTS task_definitions CASCADE;
DROP TABLE IF EXISTS TASK_EXECUTION_PARAMS CASCADE;
DROP TABLE IF EXISTS TASK_TASK_BATCH CASCADE;
DROP TABLE IF EXISTS TASK_SEQ CASCADE;
DROP TABLE IF EXISTS TASK_LOCK CASCADE;
DROP TABLE IF EXISTS TASK_EXECUTION_METADATA CASCADE;
DROP TABLE IF EXISTS TASK_EXECUTION CASCADE;

DROP TABLE IF EXISTS V2_TASK_EXECUTION_PARAMS CASCADE;
DROP TABLE IF EXISTS V2_TASK_TASK_BATCH CASCADE;
DROP TABLE IF EXISTS V2_TASK_SEQ CASCADE;
DROP TABLE IF EXISTS V2_TASK_LOCK CASCADE;
DROP TABLE IF EXISTS V2_TASK_EXECUTION_METADATA CASCADE;
DROP TABLE IF EXISTS V2_TASK_EXECUTION CASCADE;


DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_PARAMS CASCADE;
DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_CONTEXT CASCADE;
DROP TABLE IF EXISTS BATCH_STEP_EXECUTION CASCADE;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_CONTEXT CASCADE;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION CASCADE;
DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_SEQ CASCADE;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_SEQ CASCADE;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_SEQ CASCADE;
DROP TABLE IF EXISTS BATCH_JOB_SEQ CASCADE;
DROP TABLE IF EXISTS BATCH_JOB_INSTANCE CASCADE;
DROP TABLE IF EXISTS TASK_EXECUTION_METADATA_SEQ CASCADE;

DROP TABLE IF EXISTS V2_BATCH_JOB_EXECUTION_PARAMS CASCADE;
DROP TABLE IF EXISTS V2_BATCH_STEP_EXECUTION_CONTEXT CASCADE;
DROP TABLE IF EXISTS V2_BATCH_STEP_EXECUTION CASCADE;
DROP TABLE IF EXISTS V2_BATCH_JOB_EXECUTION_CONTEXT CASCADE;
DROP TABLE IF EXISTS V2_BATCH_JOB_EXECUTION CASCADE;
DROP TABLE IF EXISTS V2_BATCH_STEP_EXECUTION_SEQ CASCADE;
DROP TABLE IF EXISTS V2_BATCH_JOB_EXECUTION_SEQ CASCADE;
DROP TABLE IF EXISTS V2_BATCH_JOB_EXECUTION_SEQ CASCADE;
DROP TABLE IF EXISTS V2_BATCH_JOB_SEQ CASCADE;
DROP TABLE IF EXISTS V2_BATCH_JOB_INSTANCE CASCADE;
DROP TABLE IF EXISTS V2_TASK_EXECUTION_METADATA_SEQ CASCADE;

-- DROP TABLE IF EXISTS BOOT3_TASK_EXECUTION_PARAMS CASCADE;
-- DROP TABLE IF EXISTS BOOT3_BATCH_STEP_EXECUTION_CONTEXT CASCADE;
-- DROP TABLE IF EXISTS BOOT3_BATCH_STEP_EXECUTION CASCADE;
-- DROP TABLE IF EXISTS BOOT3_BATCH_JOB_EXECUTION_CONTEXT CASCADE;
-- DROP TABLE IF EXISTS BOOT3_TASK_LOCK CASCADE;
-- DROP TABLE IF EXISTS BOOT3_BATCH_JOB_EXECUTION_PARAMS CASCADE;
-- DROP TABLE IF EXISTS BOOT3_BATCH_JOB_EXECUTION CASCADE;
-- DROP TABLE IF EXISTS BOOT3_BATCH_JOB_INSTANCE CASCADE;
-- DROP TABLE IF EXISTS BOOT3_TASK_TASK_BATCH CASCADE;
-- DROP TABLE IF EXISTS BOOT3_TASK_EXECUTION_METADATA CASCADE;
-- DROP TABLE IF EXISTS BOOT3_TASK_EXECUTION CASCADE;
--
-- DROP SEQUENCE IF EXISTS BOOT3_BATCH_STEP_EXECUTION_SEQ;
-- DROP SEQUENCE IF EXISTS BOOT3_BATCH_JOB_EXECUTION_SEQ;
-- DROP SEQUENCE IF EXISTS BOOT3_BATCH_JOB_SEQ;
-- DROP SEQUENCE IF EXISTS BOOT3_TASK_SEQ;
-- DROP SEQUENCE IF EXISTS BOOT3_TASK_EXECUTION_METADATA_SEQ;
