CREATE SEQUENCE BOOT3_BATCH_STEP_EXECUTION_SEQ_T START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775806 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE BOOT3_BATCH_JOB_EXECUTION_SEQ_T START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775806 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE BOOT3_BATCH_JOB_SEQ_T START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775806 INCREMENT BY 1 NOCACHE NOCYCLE;

SELECT @max_value := MAX(id) FROM BOOT3_BATCH_STEP_EXECUTION_SEQ;
EXECUTE IMMEDIATE CONCAT('SELECT SETVAL(`BOOT3_BATCH_STEP_EXECUTION_SEQ_T`, ', @max_value, ')');

SELECT @max_value := MAX(id) FROM BOOT3_BATCH_JOB_EXECUTION_SEQ;
EXECUTE IMMEDIATE CONCAT('SELECT SETVAL(`BOOT3_BATCH_JOB_EXECUTION_SEQ_T`, ', @max_value, ')');

SELECT @max_value := MAX(id) FROM BOOT3_BATCH_JOB_SEQ;
EXECUTE IMMEDIATE CONCAT('SELECT SETVAL(`BOOT3_BATCH_JOB_SEQ_T`, ', @max_value, ')');

DROP TABLE BOOT3_BATCH_STEP_EXECUTION_SEQ;
DROP TABLE BOOT3_BATCH_JOB_EXECUTION_SEQ;
DROP TABLE BOOT3_BATCH_JOB_SEQ;

ALTER TABLE BOOT3_BATCH_STEP_EXECUTION_SEQ_T RENAME TO BOOT3_BATCH_STEP_EXECUTION_SEQ;
ALTER TABLE BOOT3_BATCH_JOB_EXECUTION_SEQ_T RENAME TO BOOT3_BATCH_JOB_EXECUTION_SEQ;
ALTER TABLE BOOT3_BATCH_JOB_SEQ_T RENAME TO BOOT3_BATCH_JOB_SEQ;
