name: CI IT Security

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  test:
    name: Security IT
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'liberica'
    - uses: jvalkeal/setup-maven@v1
      with:
        maven-version: 3.8.8
        maven-mirror: 'https://dlcdn.apache.org/maven/maven-3/'
    - name: Login dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Run Security IT
      env:
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      run: |
        mvn clean install -DskipTests -T 1C -s .settings.xml -pl spring-cloud-dataflow-server -am
        mvn \
          -s .settings.xml \
          -pl spring-cloud-dataflow-server \
          -Dgroups=oauth \
          -Pfailsafe \
          --batch-mode \
          test
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: ${{ success() || failure() }}
      with:
        name: Integration Tests
        path: '**/surefire-reports/*IT.xml'
        reporter: java-junit
        list-tests: failed
    - name: 'Action: Upload Integration Test Results'
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.group }}-test-results-failsafe
        path: './**/target/failsafe-reports/**/*.*'
        retention-days: 7
        if-no-files-found: ignore
