server:
  port: 9393
management:
  contextPath: /management
  security:
    enabled: false
info:
  app:
    name: "@project.artifactId@"
    description: "@project.name@"
    version: "@project.version@"
security:
  basic:
    enabled: false

maven:
  remoteRepositories:
    springRepo:
      url: https://repo.spring.io/libs-snapshot

spring:
  application:
    name: spring-cloud-dataflow-server-local
  cloud:
    config:
      uri: http://localhost:8888
  datasource:
    url: jdbc:h2:tcp://localhost:19092/mem:dataflow
    username: sa
    password:
    driverClassName: org.h2.Driver
  task:
    repo:
      initialize: true
  dataflow:
    embedded:
      database:
        enabled: true
